### ISSUE TITLE
Propagate errors via a (result, error) tuple

### ISSUE THREAD

**Issue by alecthomas** [alexeyxo/protobuf-swift#10]
Swift code seems to be converging on returning tuples of `(ResultType?, Error?)` as "error handling best practice". With no way to natively catch exceptions in Swift, using NSException makes handling protobuf errors particularly difficult. I understand that it is probably significantly easier to throw an exception than to propagate result values, but it seems like it would be a better approach long term. What do you think?

**Comment by alecthomas** [comment]
Hi Alexey, any luck with this?

**Comment by alexeyxo** [comment]
Hi, i haven't more time.I do not have time yet.

**Comment by vgatto** [comment]
+1, it would be great to have this.

**Comment by alexeyxo** [comment]
Swift 2.0 has error handling. This issue isn't actual any more.
