### ISSUE TITLE
Custom Options and using a swift descriptor

### ISSUE THREAD

**Issue by heromyst** [alexeyxo/protobuf-swift#105]
Hey guys,

Currently I have a common set of proto3 .proto files for multiple different languages and I want the scope of these files to be public (especially for Swift because I'm including these generated classes in a framework that can be used by multiple projects, hence the classes all have to be public. 

Is there a better way to default the generation to public class scope instead of importing the swift-descriptor into every file? (Which would be problematic when generating these files for non-Swift languages). A method for only the Swift generation to have these custom options would also be nice. Is there a way I can achieve this right now without too much platform-specific code such as Swift custom options?

Thanks,
Vic

**Comment by alexeyxo** [comment]
Unfortunately, not possible. You should generate swift-descriptor for all languages.
