### ISSUE TITLE
Couple of questions regarding windows support and direction of this plugin

### ISSUE THREAD

**Issue by heromyst** [alexeyxo/protobuf-swift#107]
Hey there,

I have a couple of questions regarding this protobuf-swift plugin. 

1. Is there any windows support for this? If I want to run this on windows would I be able to? 

2. This is a more general question against the direction of this plugin. Is there any ideas for continuous integration and integration into build systems? Or are end-users expected to write scripts that incorporate this plugin. I'm trying to use this in a larger continuous build system.

Thanks,
Vic

**Comment by alexeyxo** [comment]
Unfortunately, I can't answer your questions because I do not use windows.

**Comment by DouglasHeriot** [comment]
@heromyst 

I have a cross-platform app that runs on Mac/Windows/Linux. However, my Swift code only runs on Mac, so I only need protobuf-swift on Mac.

I use CMake to manage the build process of all the supporting libraries (ie. protobuf itself), but conditionally only compile protobuf-swift for Mac.

Unless you have Swift code running on Windows (which I think is experimental-only state by Microsoft?) you shouldn’t need to ever compile protobuf-swift on Windows.
