### ISSUE TITLE
Redeclaration of Struct in generated .swift file

### ISSUE THREAD

**Issue by heromyst** [alexeyxo/protobuf-swift#108]
I have 2 .proto files under the same package namespace.

//File 1
syntax = "proto3";
package abc.efg.hij;

message Test {
  string id = 1;
}

//File 2
syntax = "proto3";
package abc.efg.hij;

message Test2 {
  string description = 1;
}

The generated .swift file declares the struct: 
public struct abc { public struct efg { public struct hij { }}}

at the top of the file which will be a redeclaration if I have more than 1 .proto file with the same package.

Is this intended?

Thanks,
Vic

**Comment by alexeyxo** [comment]
You should generate in one "pipeline".
Try this:
```protoc *.proto --swift_out="./"```

**Comment by heromyst** [comment]
This works for me thanks. Just had to generate them all together.
