### ISSUE TITLE
Memory leak/zombie object

### ISSUE THREAD

**Issue by appsbg** [alexeyxo/protobuf-swift#113]
How to free the memory here:
var parsedData : Test = try Test.parseFromData(data)
It looks that I get a zombie object - memory is never released

**Comment by appsbg** [comment]
There is definately a huge leak in parseFromData. Please take a look at it

**Comment by alexeyxo** [comment]
I need  "proto" file example.

**Comment by appsbg** [comment]
I have 	
required string name = 1; 
required bytes dt = 2;
Look what I found, I'm not 100% sure yet but it looks that the leak is gone if I replace CodedInputStream.swift:44  with: `buffer = NSMutableData(bytesNoCopy: UnsafeMutablePointer<Void>(aData.bytes), length: aData.length, freeWhenDone: false)`

**Comment by appsbg** [comment]
or at least is much smaller, still needs fixing though

**Comment by alexeyxo** [comment]
I can't find memory leaks. In my profiler all working fine. Maybe, you have screenshots or "step by step" example, how to reproduce?
