### ISSUE TITLE
Crash when parsing JSON containing empty array 

### ISSUE THREAD

**Issue by amleszk** [alexeyxo/protobuf-swift#114]
I have a proto file:
```
message Connections {
    message Connection {
    }
    repeated Connection connections = 1;
}
```

and the JSON looks like:
```
{\"connections\": [] }
```

[![enter image description here][1]][1]

This crashes protobuffers, any ideas? thanks

  [1]: http://i.stack.imgur.com/2a5nz.png

**Comment by alexeyxo** [comment]
The error in the screenshot is not associated with Protobuf.
