### ISSUE TITLE
General ( OSX / Linux ) Does not compile after running protoc

### ISSUE THREAD

**Issue by jabwd** [alexeyxo/protobuf-swift#115]
The method:
`
override internal func writeDescriptionTo(inout output:String, indent:String) throws {`

Is marked as an override but does not actually override anything thus returning an Error. Trying to print out a description will crash your app with this removed.

**Comment by alexeyxo** [comment]
Get me more information. I think you have something wrong doing.

**Comment by jabwd** [comment]
Build cmd used:
`protoc Messages.proto --swift_out="./"`

Proto file:
[Messages.txt](https://github.com/alexeyxo/protobuf-swift/files/138235/Messages.txt)

The supplied Xcode project for the ProtocolBuffers framework is included and embedded in the application.

**Comment by alexeyxo** [comment]
You used old framework or compiler.

**Comment by PaulZMJun** [comment]
which is the newest framework. Which version. My protcobuf's version is 2.6.1, protobuf-swift is 2.4.3
