### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.9.dylib

### ISSUE THREAD

**Issue by romainmenke** [alexeyxo/protobuf-swift#118]
#### Description

    dyld: Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.9.dylib

Seems there is a new version of libprotobuf.10.dylib

Issue seems to be here : /protobuf-swift/plugin/compiler/google/protobuf/stubs/substitute.h line:140 line:153

I would mess with it myself, but way out of my comfort zone.

Greetings!

**Comment by alexeyxo** [comment]
How you installed the library?

**Comment by romainmenke** [comment]
I only have version libprotobuf.10.dylib.
Is it ok to have both? Or am I missing something else entirely?

**Comment by alexeyxo** [comment]
You should install **protobuf-swift** from ```Protobuf3.0-Swift2.0``` branch.

**Comment by romainmenke** [comment]
Works like a charm, thank you for the speedy responses!

**Comment by xtea** [comment]
Thanks , I solve this problem using :
```
brew uninstall protobuf-swift
brew install  protobuf-swift
```

**Comment by Yourney** [comment]
I have the exact same.
I just updated from ProtocolBuffers 2.6.1 to 3.1.
I have protobuf-swift, have 3.0.6 now.
When I call protoc-gen-swift --version
I get:
dyld: Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.9.dylib
  Referenced from: /usr/local/bin/protoc-gen-swift
  Reason: image not found
Should I have a new version of protoc-gen-swift ?
How do I get that?

**Comment by oilcake** [comment]
Can you please tell me where can I find **libprotobuf.28.dylib**?
