### ISSUE TITLE
Sending proto via socket to c++ with data loss

### ISSUE THREAD

**Issue by JoseVigil** [alexeyxo/protobuf-swift#119]
Hi, 

I ran out of ideas, trying to send the swift protobuf from ios to c++ via socket and I encountered data loss on string format and inconsistency. I am encoding with base64 like this.

**Building, serializing and sending:**

### **Edited with right answer.
```
let messageBuilder = Motion.Message_.Builder()
messageBuilder.types = Motion.Message_.ActionType.Engage
messageBuilder.serverip = "192.168.0.5"
let packagesize       = Int32(Motion.Message_.SocketType.SocketBufferNanoSize.rawValue)
messageBuilder.packagesize = packagesize
messageBuilder.includethubmnails = false

//Strings
messageBuilder.imagefilepath = "kdafkdfhkjasdhfkaskdjfhaksdjfhasdhf"
messageBuilder.devicestarttime = "kdfasdfouiasdhfhasuidhifduhiuhfsuidauidhfiuasdhiuf"

//Bytes
let str = "Mea ea aperiri accusamus, euismod explicari et sit. Et nam aliquando interesset, altera euripidis an sit, regione petentium cu per. Latine dissentias eos et. Pro debet ullamcorper ea, mea inani feugait ex, vide reprehendunt eos ei. Has id similique complectitur, et malis atomorum vix, est errem vulputate efficiendi ne."

let data = (str as NSString).dataUsingEncoding(NSUTF8StringEncoding)
messageBuilder.datafile = data!

//Sending
var dataencoded = String()
            
do
{
    let m = try messageBuilder.build()
    
    let data:NSData = m.data()

    //Encode             
    dataencoded = data.base64EncodedStringWithOptions(NSDataBase64EncodingOptions(rawValue: 0))
        
} catch
{
    print(error)
}
//Send base64
var (success,errmsg) = client.send(str: dataencoded)
```

**Deserialized with C++:**

Check the output on the c++ end after SerializeToArray and decode, notice the datafile (bytes) field contains string data (broken) but there are fields missing data. The initial value of type is the only field allways sent, the others are sent randomnly.

> type:1000
> serverip:
> packagesize:0
> includethubmnails:0
> imagefilepath:
> datafile:Mea ea aperiri accusamus, euismod explicar
> devicestarttime:

Same applies when I send string instead of bytes. 

**Proto:**

```
syntax = "proto2";
package motion;  
  
message Message 
{    
	
	required ActionType type 			= 1 [default = ENGAGE];
	optional string serverip 			= 2;
	optional int32 packagesize 			= 3;
	optional bool includethubmnails 	= 4;
	optional string imagefilepath 		= 5; 
	optional string videofilepath 		= 6;
	optional bytes datafile				= 7;
	
	enum ActionType 
	{
		ENGAGE              = 1000;
		REC_START			= 1002;
		REC_RUNNING			= 1003;
		REC_STOP	        = 1004;
		UNENGAGE            = 1005;
	}

	enum SocketType
	{
		SOCKET_BUFFER_NANO_SIZE     = 1024;
		SOCKET_BUFFER_MINI_SIZE     = 2048;
		SOCKET_BUFFER_MICRO_SIZE    = 4096;
	}

}
```

Options: 

- [Protobuf-swift](https://github.com/alexeyxo/protobuf-swift) does not support encoding and used via socket (weird if so).

- I have an error wrapping up the data (hopefully). 

- Move to [ObjectiveC ](http://protobuf.axo.io/#objc)protobuf version (possible).

- Move to C++ via ObjectiveC++ (more complex).

**Comment by alexeyxo** [comment]
I have no problems to sending protobuf through socket. I think your problems in transport.

**Comment by JoseVigil** [comment]
Hi Alex, 

Your tip showed me the way to the answe. The enconding options for base64EncodedStringWithOptions, I had to use `NSDataBase64EncodingOptions(rawValue: 0)` instead of `Encoding64CharacterLineLength`.

Edited above.

Thanks for the answer.
Jose
