### ISSUE TITLE
Install with protobuffer from brew

### ISSUE THREAD

**Issue by brasilikum** [alexeyxo/protobuf-swift#120]
#### Description
You can now install protobuffer from brew:
```
brew install --devel protobuf
```

So after I installed protobuf-swift:

```
brew install protobuf-swift
```
I get the following output no matter which source dir:

```
protoc --swift_out=swift *.proto
dyld: Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.9.dylib
  Referenced from: /usr/local/bin/protoc-gen-swift
  Reason: image not found
--swift_out: protoc-gen-swift: Plugin killed by signal 5.
```

Does brew not put the lib in /usr/local/opt/protobuf/lib/libprotobuf.9.dylib?

**Comment by romainmenke** [comment]
You version 10 of libprotobuf. Check out [https://github.com/alexeyxo/protobuf-swift/issues/118](same issue)
