### ISSUE TITLE
building issue

### ISSUE THREAD

**Issue by arielzadi** [alexeyxo/protobuf-swift#121]
#### ```.proto``` file to reproduce
```protobuf
syntax = "proto2";
message Perfomance
{
  required int32 ints = 1;
  required int64 ints64 = 2;
  required double doubles = 3;
  required float floats  = 4;
  optional string str  = 5;
  optional bytes bytes  = 6;
  optional string description = 7;
}
```

#### Description
can't manage to make Xcode compile a protobuf generated class from a test message correctly.
after creating the test message "performance"(see above) and compiling with protoc i have added it to my project

Xcode tells me

.../iOSProtos/Perfomance.proto.swift:183:26: Method does not override any method from its superclass

this is the auto generated method:
override internal func writeDescriptionTo(inout output:String, indent:String) throws {

and second error is

../iOSProtos/Perfomance.proto.swift:205:5: Value of type 'UnknownFieldSet' has no member 'writeDescriptionTo'

this is the line(and it is inside the problematic function from above:
unknownFields.writeDescriptionTo(&output, indent:indent)

please note:
i need to stay with compiler version 2.6.1 to be compatible with my java project

**Comment by alexeyxo** [comment]
You used oldest version of protobuf-swift compiller.
