### ISSUE TITLE
swift3 and latest 18.03 devel snapshot  compatibility

### ISSUE THREAD

**Issue by goloveychuk** [alexeyxo/protobuf-swift#122]
https://github.com/goloveychuk/protobuf-swift/commit/9896357981fc2bc2d311c33a181b6d41390e7153

**Comment by gegles** [comment]
Hello, I just wanted to ask if there was active work being done on the latest Swift 3.0 compatibilty (June 6th snapshot for example)? Especially with the massive new renaming changes....

Any estimate as to when this would be available?

I am still a bit new to Swift, but I don't mind helping a bit if I can...

Thanks. G.

**Comment by goloveychuk** [comment]
there is already swift 3 branch. As I remember there were two big changes
1) first arg in function call is named by default
2) optional unsafepointers. 
I'll look at this tomorrow

**Comment by gegles** [comment]
Thanks for looking into it!

Sorry I wasn't clear, I am using the Proto3-Swift3 branch but there are many hundreds of changes when running the Swift Migration tool ......... and obviously, beyond the library fixes, there is also code generation code that may need to be adjusted...

**Comment by alexeyxo** [comment]
Done.
