### ISSUE TITLE
Method does not override any method from its superclass

### ISSUE THREAD

**Issue by thalmicMark** [alexeyxo/protobuf-swift#126]
#### ```.proto``` file to reproduce
```protobuf
syntax="proto2";
package com.test.handshake;

message Handshake { }

message HandshakeResponse { }
```

#### Description

I've also got `protobuf (2.6.1)` and `protobuf-swift (2.2)` installed. I installed `ProtocolBuffers.framework` from [here](https://github.com/alexeyxo/protobuf-swift/releases/tag/2.4.3).

I get the following errors after creating `.swift` files from `.proto` files.

    override internal func writeDescriptionTo(inout output:String, indent:String) throws { // Method does not override any method from its superclass
      unknownFields.writeDescriptionTo(&output, indent:indent) // Value of type 'UnknownFieldSet' has no member 'writeDescriptionTo'
    }

**Comment by alexeyxo** [comment]
You used oldest version of protobuf-swift.

**Comment by thalmicMark** [comment]
How would I get the newest version? I followed the `README` and installed via homebrew.

**Comment by thalmicMark** [comment]
For reference, it looks like the home-brew version is out of date. Building via the included scripts builds the latest.

**Comment by anuragedushire** [comment]
I am facing the same issue and have not been able to fix this yet. Which branch did you finally build to make it work?

**Comment by anuragedushire** [comment]
Master works. For me, xcode was troubling because it had cached libraries.
