### ISSUE TITLE
Duplicate declaration of package

### ISSUE THREAD

**Issue by spearway** [alexeyxo/protobuf-swift#137]
#### Version of protoc (```protoc --version```)
libprotoc 2.6.1

#### ```.proto``` file to reproduce
I have created a script in Xcode of compile my protobufs

PROTO_DEFINITION="--proto_path=/usr/local/include/"

OUTPUT_PATH=${SCRIPT_OUTPUT_FILE_0}

for (( c=0; c<${SCRIPT_INPUT_FILE_COUNT}; c++ ))
do
    PROTO_INPUT_DIRECTORY=SCRIPT_INPUT_FILE_${c}
    PROTO_INPUT_DIRECTORY_PATH=${!PROTO_INPUT_DIRECTORY}/

    PROTO_DEFINITION="--proto_path=${PROTO_INPUT_DIRECTORY_PATH} ${PROTO_DEFINITION}"

    LOWEERCASEPREFIX=`basename ${PROTO_INPUT_DIRECTORY_PATH}`
    OUTPUT="${OUTPUT_PATH}/${LOWEERCASEPREFIX}"

    mkdir -p ${OUTPUT}

    PROTOBUFS=`ls -1 ${PROTO_INPUT_DIRECTORY_PATH}*.proto`

    for PROTBUF in ${PROTOBUFS};
    do
    if [[ -e "$PROTBUF" ]];
    then
        echo ${PROTBUF}
        protoc  --swift_out=${OUTPUT}  ${PROTO_DEFINITION}  ${PROTBUF}
    fi
    done

done

#### Description
I have a problem with the package definition I am reusing protobuf declaration that were done for Java and Scala and I cannot modify them but I need to use them in Swift.

[auxdata.zip](https://github.com/alexeyxo/protobuf-swift/files/268554/auxdata.zip)
[auxdata.zip](https://github.com/alexeyxo/protobuf-swift/files/268555/auxdata.zip)

Each of the files include on message and start with a package declaration like:

package auxdata;
option java_package = "com.apple.geo.auxdata";
option java_outer_classname = "AddressConflation";
import "Extensions.proto";
message AddressConflationInfo {
    optional fixed64 feature_id = 1 [(neutron.is_required) = true];
    repeated string cluster_street_names = 2;
    repeated string cluster_building_names = 3;
}

This is translated in the Swift file with a 

public struct Auxdata { }

The problem is that I get one of those for each file which the compiler complain as duplicate…

**Comment by alexeyxo** [comment]
You should generate package in one pipeline:
For example:
```sh
protoc *.proto --swift_out="./" 
```

**Comment by spearway** [comment]
Ok I found the problem I was working too hard I should have put all the file in the same package in the same compilation unit. That being said I would suggest an improvement that could get us out of the compilation order for Xcode. Could we generate a "package file" the only contains the original public struct package and have all other files equivalent.

**Comment by spearway** [comment]
for reference here is my script

# All protobuf relating to the same package should be compile in one unit or you will have duplicaate declarations.
# You must compile teh resulting files in order, the first file in the folder contains teh package declaration.
# The order of the input file directory is important as it defines the includes for further compilation units.


PROTO_DEFINITION="--proto_path=/usr/local/include/"

OUTPUT_PATH=${SCRIPT_OUTPUT_FILE_0}

for (( c=0; c<${SCRIPT_INPUT_FILE_COUNT}; c++ ))
do
    PROTO_INPUT_DIRECTORY=SCRIPT_INPUT_FILE_${c}
    PROTO_INPUT_DIRECTORY_PATH=${!PROTO_INPUT_DIRECTORY}/

    PROTO_DEFINITION="--proto_path=${PROTO_INPUT_DIRECTORY_PATH} ${PROTO_DEFINITION}"

    LOWEERCASEPREFIX=`basename ${PROTO_INPUT_DIRECTORY_PATH}`
    OUTPUT="${OUTPUT_PATH}/${LOWEERCASEPREFIX}"

    mkdir -p ${OUTPUT}

    PROTOBUFS=`ls -1 ${PROTO_INPUT_DIRECTORY_PATH}*.proto`
    echo ${PROTOBUFS} | xargs protoc --swift_out=${OUTPUT} ${PROTO_DEFINITION}

done

**Comment by spearway** [comment]
Thank you
