### ISSUE TITLE
At wits end trying to install for Swift 2.0 / Protobuf 3 

### ISSUE THREAD

**Issue by gmckenzi** [alexeyxo/protobuf-swift#139]
Sorry for using an issue for this purpose but I've read through the following other related issues:

- #118 dyld: Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.9.dylib
- #120 Install with protobuffer from brew

I've cloned the ProtoBuf3.0-Swift2.0 branch and run build.sh. in hopes of getting Swift 2.0 support.
I've run `brew install protobuf --devel` to get Protobuf 3 support.

But I still get the dreaded `dyld: Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.9.dylib` error when running.

Any chance of having something written up in the Wiki or the readme on how to install a Swift 2 / Protobuf 3 configuration?

**Comment by alexeyxo** [comment]
Try this:
```
rm -f /usr/local/opt/protobuf/lib/libprotobuf.9.dylib

brew remove protobuf

brew install protobuf --devel
```

**Comment by gmckenzi** [comment]
I nuked everything and started again, including your steps and everything is great now.
Thank you.
