### ISSUE TITLE
Runtime access control change.

### ISSUE THREAD

**Issue by tetek** [alexeyxo/protobuf-swift#140]
Hi, great work @alexeyxo.

I'm working on a framework, and I've added ProtocolBuffer runtime classes to my framework. (I don't want dependencies).
The problem is that all the classes in `Source` are `public`.
I've no problem with my messages since I add a compilation flag for them to be internal.
Is there any easy solution other then changing all `plugin/compiler/google/protobuf` access level and recompiling?

**Comment by alexeyxo** [comment]
Hi! You should use custom options.
https://github.com/alexeyxo/protobuf-swift#custom-options
