### ISSUE TITLE
Difference between rpc_id and rpcId

### ISSUE THREAD

**Issue by flypaper0** [alexeyxo/protobuf-swift#154]
Hello!

I compiled my .proto with  protobuf-swift, some filed have been changed.

`message RequestEnvelop {
  required int32 unknown1 = 1;
  optional int64 rpc_id = 3;
  repeated Requests requests = 4;
}
`

For example 'rpc_id' is 'rpcId' in .proto.swift

`  message Requests {
    required int32 type = 1;
    optional bytes message = 2;
  }
`

and 'type' is 'types'. Will this affect the validity of the final request?

For more info that's how i build request (may be i do something wrong)

  let tokenBuilder = RequestEnvelop.AuthInfo.Jwt.Builder()
  tokenBuilder.contents = idToken
  tokenBuilder.unknown13 = 14
  let token = try! tokenBuilder.build()

  let authBuilder = RequestEnvelop.AuthInfo.Builder()
  authBuilder.provider = "google"
  authBuilder.token = token
  let auth = try! authBuilder.build()

  let requestsTypes: [Int32] = [2, 126, 4, 129, 5]
  var requests: [RequestEnvelop.Requests] = []
  for requestsType in requestsTypes {
    let requestBuilder = RequestEnvelop.Requests.Builder()
    requestBuilder.types = requestsType
    let request = try! requestBuilder.build()
    requests.append(request)
  }

  let requestEnvelopBuilder = RequestEnvelop.Builder()
  requestEnvelopBuilder.rpcId = 1469378659230941192
  requestEnvelopBuilder.unknown1 = 2
  requestEnvelopBuilder.latitude = UInt64(4633020688021586927)
  requestEnvelopBuilder.longitude = UInt64(4630497334661170120)
  requestEnvelopBuilder.altitude = 0
  requestEnvelopBuilder.unknown12 = 989
  requestEnvelopBuilder.auth = auth
  requestEnvelopBuilder.requests = requests

  let requestEnvelop = try! requestEnvelopBuilder.build()
  let protobuf = requestEnvelop.data()

**Comment by alexeyxo** [comment]
Field named as "Type" is reserved in Swift. Protobuf does not use field name for serializing/deserializing of data. In Protobuf-Swift3.0 all reserved fields marke as `<field>`.
