### ISSUE TITLE
memory use rising high

### ISSUE THREAD

**Issue by leoouc** [alexeyxo/protobuf-swift#157]
#### ```.proto``` file to reproduce
```protobuf
syntax = "proto2";
message Person {
    required string name = 1;
    required bytes data=2;
}
```

#### Description
I  use 2.4.1,and write a simple test case, the memory usage keep rising, is that memory leaks? and code as following
func beginTest() {
        var i = 0;
        let fileManager = NSFileManager.defaultManager()
        let mydir = NSHomeDirectory() + "/Documents/myfolder/test/"
        let d:NSString = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        do{
            try fileManager.createDirectoryAtPath(mydir , withIntermediateDirectories: true, attributes: nil)
            let pathString = mydir + "q.txt"

            while i < 100000000 {
                i = i+1;
                let a = Person.Builder()
                a.setName(String(i))
                a.setData(d.dataUsingEncoding(NSUTF8StringEncoding)!)
                try a.build().data.writeToFile(pathString, atomically: true)
            }
        }catch{
            print(error)
        }        
    }

**Comment by alexeyxo** [comment]
Swift language has memory leak when objects are bridge to objc from swift and backward. This example is not obvious.
