### ISSUE TITLE
Duplicate type declaration

### ISSUE THREAD

**Issue by agisboye** [alexeyxo/protobuf-swift#158]
#### ```.proto``` file to reproduce
[https://github.com/AeonLucid/POGOProtos](https://github.com/AeonLucid/POGOProtos)

#### Description
I'm trying to compile the .proto files from the repository that I've linked to. The files are organized into various packages, and they import each other. I.e. they all have the same base package (not sure if this is the correct terminology):
```protobuf
package POGOProtos.Data.Battle;
```

This causes problems when generating the swift files.

Rather than nesting the package declarations by using extensions, the containing packages for each message are redeclared in every .swift file. Every single swift file generated by protoc redeclares the base package:
```swift
public struct Pogoprotos { public struct Data { public struct Battle { }}}

public extension Pogoprotos.Data.Battle {
...
}
```

I've tried compiling by using the python scripts in the linked repository as well as by running the following command inside the repo:
`find ./src -name "*.proto" -exec protoc --proto_path="./src" --swift_out="./out/" '{}' ';'`

Is this an issue with the library or the way I'm using it? Is it because I'm running protoc on each .proto file individually?

**Comment by alexeyxo** [comment]
Try this:
https://github.com/alexeyxo/protobuf-swift/issues/137
