### ISSUE TITLE
Error handle error

### ISSUE THREAD

**Issue by thandang** [alexeyxo/protobuf-swift#160]
#### ```.proto``` file to reproduce
```protobuf

```

#### Description
I got a lot of errors when running in Xcode with compile result. 
I showed that 
`call can throw, but it is nor marked with 'try' and the error is not handled`
Can we have a fix that?

Kind regards,
Than Dang

**Comment by alexeyxo** [comment]
Get me example. How does you use ```try```?

**Comment by thandang** [comment]
You have to input try! before an invoke function to fix the error. And I think the problem was about swift version, isn't it?

**Comment by thandang** [comment]
Here is the error I get [https://monosnap.com/file/qXxX8LEuYJxT3SMVHFlDnk4pgsvCoA](url)

**Comment by alexeyxo** [comment]
You use very oldest version of protobuf-swift.

**Comment by thandang** [comment]
hmm, let me check. Thanks a lot.

**Comment by thandang** [comment]
Cool, great help. Thank you so much. What I missing is not follow all step of installation by thinking about use CocoaPod instead. But the last step `7.Add ./src/ProtocolBuffers/ProtocolBuffers.xcodeproj in your project.` we don't need actually.
