### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by jault3** [alexeyxo/protobuf-swift#161]
###### n/a

I am on the latest code with the master branch.

#### ```.proto``` file to reproduce

n/a

#### Description

`protoc --swift_out` does not exist. I run `./scripts/build.sh` and then `protoc --help` and don't see the option listed. The end of the build output looks like this

```
+ make install
Making install in plugin/compiler
 ../.././install-sh -c -d '/usr/local/bin'
  /bin/sh ../../libtool   --mode=install /usr/bin/install -c protoc-gen-swift '/usr/local/bin'
libtool: install: /usr/bin/install -c protoc-gen-swift /usr/local/bin/protoc-gen-swift
make[2]: Nothing to be done for `install-data-am'.
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
```

perhaps it's not installing or building correctly? I can provide more information, just wasn't sure what was relevant or needed.

**Comment by alexeyxo** [comment]
Installation was successful.

**Comment by alexeyxo** [comment]
Yes, you should include this or install from cocoapods or etc.
