### ISSUE TITLE
Message Repeated enum mergFromData Error

### ISSUE THREAD

**Issue by 13812453806** [alexeyxo/protobuf-swift#166]
#### ```.proto``` file to reproduce
message IToken {
enum ITokenType {
        ATT_NO_USE = 0; 
        ATT_ONCE = 1; 
        ATT_ONCE_IP = 2; 
        ATT_TIME = 3; 
        ATT_FOREVER = 4; 
    }
repeated ITokenType itt= 4;
}

#### Description

this proto build to swift can not mergFromData from base64

**Comment by alexeyxo** [comment]
Please, add more description and example about the problem.

**Comment by alexeyxo** [comment]
this method works only with binary pb data format without encode.

**Comment by 13812453806** [comment]
Repeated enum encode to base64 string, then decode from this base64 String will crash
