### ISSUE TITLE
Enhancement request: Update codebase to latest Swift3 (Xcode 8 Beta 6)

### ISSUE THREAD

**Issue by gegles** [alexeyxo/protobuf-swift#168]
#### ```.proto``` file to reproduce
```protobuf

```

#### Description

Unlike previous updates, this one is not as trivial (for a novice like me). Especially Swift3 changes regarding scope (open,public,private, fileprivate) require a more intimate understanding of the protobuf-swift codebase.

**Comment by felixLam** [comment]
Hi there, I started working on it in #169

**Comment by gegles** [comment]
Thanks for the work @alexeyxo and @felixLam. I tried the latest, but I still get a bunch of errors related to AnyObject .... I've recompiled my .proto using the latest compiler.....

For now, I'll stick with beta-5.... but I'll keep trying as thinks evolve.

Cheers. G.

**Comment by alexeyxo** [comment]
Done for Protobuf 3.0.

**Comment by gegles** [comment]
Thanks, it works! (for me at least)
