### ISSUE TITLE
CocoaPods Support

### ISSUE THREAD

**Issue by alexeyxo** [alexeyxo/protobuf-swift#17]
https://github.com/CocoaPods/CocoaPods/issues/2272
https://github.com/CocoaPods/CocoaPods/pull/2222

**Comment by tcf1991** [comment]
public func readData() throws -> Data {
        let size = Int(try readRawVarint32())
        if size < bufferSize - bufferPos && size > 0 {
//            let pointer = UnsafeMutablePointerInt8From(data: buffer)
            let unsafeRaw = UnsafeRawPointer(&buffer+bufferPos)
            let data = Data(bytes: unsafeRaw, count: size)
            bufferPos += size
            return data
        } else {
            return try readRawData(size: size)
        }
    }
