### ISSUE TITLE
Expected top-level statement error

### ISSUE THREAD

**Issue by meysam-h** [alexeyxo/protobuf-swift#171]
#### ```.proto``` file to reproduce
```protobuf

```

#### Description
i was installed protobuf in my osx, when i want to compile .proto file, i receive same error:
Expected top-level statement (e.g. "message").
Unmatched "}".

what I have to do?

**Comment by alexeyxo** [comment]
Show me your .proto file, please.

**Comment by alexeyxo** [comment]
I think you have error in .proto file.

**Comment by meysam-h** [comment]
message ConnectionSecuringResponse {
    Response response = 1;
    string public_key = 2;
    uint32 symmetric_key_length = 3;
}

**Comment by alexeyxo** [comment]
Where you define "Response?"

**Comment by meysam-h** [comment]
i dont define "Response", but also I receive error without "Response"
