### ISSUE TITLE
Reserved Keyword Escaping

### ISSUE THREAD

**Issue by Pmaene** [alexeyxo/protobuf-swift#172]
#### ```.proto``` file to reproduce
```protobuf
syntax = "proto3";

import "google/protobuf/swift-descriptor.proto";
option (.google.protobuf.swift_file_options).class_prefix = "Native";

enum Type {
    INIT = 0;
}
```

#### Description

First of all, thanks a lot for keeping up with all the changes in each new Xcode beta release! When compiling this ProtoBuf 3.0 specification for Swift, two errors related to reserved keyword escaping pop up:

1. The prefixed return type of functions which return have an instance of Type as their result, will be incorrectly escaped as Native\`Type\`, instead of NativeType.
2. On the other hand, the INIT element of the enum will not be escaped. It is mapped to .ini, and not .ìnit`.

**Comment by DouglasHeriot** [comment]
I just ran into a similar issue – I think my pull request #173 fixes your second `init` case.
Since I’m in the area, I also had a go at fixing your first case too (haven’t tested it though). Issue seems to be it was going through the `SafeName` filter before concatenating your prefix on.

**Comment by Pmaene** [comment]
Thanks for the quick replies @DouglasHeriot and @alexeyxo! Even when correctly escaped, the second case does not work. It seems there's a compiler bug that prevents an "init" enum element from working correctly (https://bugs.swift.org/browse/SR-1660).
