### ISSUE TITLE
dynamic instance 

### ISSUE THREAD

**Issue by meysam-h** [alexeyxo/protobuf-swift#175]
#### ```.proto``` file to reproduce
```protobuf

```

#### Description
i want to create object of my proto, with name and use its functions (dynamic instance), what can I do?!

**Comment by alexeyxo** [comment]
Example, please.

**Comment by meysam-h** [comment]
i want same code:

        let className = "myProjectName.Person"
        
        let aClass = NSClassFromString(className)
        
        let ClassBuild = aClass.Builder().build()
        
        ClassBuild.name = "Name"

**Comment by alexeyxo** [comment]
NSClassFromString - worked only with child of NSObject. You can use solutions with dynamicType.

**Comment by umbri** [comment]
Any solution on this ?
