### ISSUE TITLE
Update CocoaPods version to 3.0.0

### ISSUE THREAD

**Issue by mihaibulic** [alexeyxo/protobuf-swift#178]
Since iOS 10 & Xcode 8 have rolled out publically, could you push version 3.0.0 to CocoaPods so we can migrate to Swift 3?

Thanks

**Comment by alexeyxo** [comment]
Hi! Currently, cocoapods not supporting Swift3.0:(.
I get many errors:
```
 - ERROR | xcodebuild:  ProtocolBuffers-Swift/Source/AbstractMessage.swift:141:36: error: thrown expression type 'ProtocolBuffersError' does not conform to 'ErrorType'
```

**Comment by mihaibulic** [comment]
I use CocoaPods for many other libraries (AlamoFire, KingFisher, etc.) and they have all pushed new versions that support Swift 3.0, so I do not believe this is the case

**Comment by alexeyxo** [comment]
Done.
