### ISSUE TITLE
Problem with handling implied packing in Proto3

### ISSUE THREAD

**Issue by gmckenzi** [alexeyxo/protobuf-swift#179]
#### ```.proto``` file to reproduce
```protobuf
syntax = "proto3";
package Test;

enum Instructions
{
    InstructionA = 0;
    InstructionB  = 1;
    InstructionC  = 2;
}

message Value 
{
	bool   b = 1;
}

message Expression
{
    repeated Instructions code	= 1;
	repeated Value data			= 2 [packed=false];
}
```

#### Description

My understanding is that in Protobuf v3, packing is turned on by default. However, the Protobuf docs also add this bit of complication: 

> Protocol buffer parsers must be able to parse repeated fields that were compiled as packed as if they were not packed, and vice versa.

So, the above sample protobuf file is derived from a client project I'm working on. The Expression message contains a repeated Instructions enum, and a repeated Value message. The Value message is not relevant to this problem except to point out that in my client's protobuf definition they leave "packed=true" off the Instructions part because packing is implied in Protobuf v3, and therefore they explicitly say "packed=false" on the value part because for some reason they don't want the repeated values to be packed.

When I compiled this .proto file to Swift, it generates code which apparently assumes a "packed=false" behaviour for the repeated Instructions enum. This is a problem because the client's server is packing the repeated Instructions enum.

When I compile this .proto to Go and run the sample program, I can see that Go packs the Instructions by default.

```go
package main

import "log"
import proto "github.com/golang/protobuf/proto"
import pb "Test"

func main() {
	expr := &pb.Expression{Code: []pb.Instructions{pb.Instructions_InstructionA, pb.Instructions_InstructionB}}
	data, _ := proto.Marshal(expr)
	log.Printf("Go: %x\n", data)
}
```

It produces the following output:

`Go: 0a020001`

So, the leading byte is 10, indicating the beginning of the packing.

When I look at the Swift code generated, I see this section:

```swift
      override public func mergeFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Test.Expression.Builder {
        let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(copyFrom:self.unknownFields)
        while (true) {
          let protobufTag = try codedInputStream.readTag()
          switch protobufTag {
          case 0: 
            self.unknownFields = try unknownFieldsBuilder.build()
            return self

          case 8:
            let valueIntcode = try codedInputStream.readEnum()
            if let enumscode = Test.Instructions(rawValue:valueIntcode) {
                 builderResult.code.append(enumscode)
            } else {
                 _ = try unknownFieldsBuilder.mergeVarintField(fieldNumber: 1, value:Int64(valueIntcode))
            }
```

Note the `case 8:` instead of the expected `case 10`.

If I modify the .proto file to force packing on for the repeated Instructions enum...

```protobuf
syntax = "proto3";
package Test;

enum Instructions
{
    InstructionA = 0;
    InstructionB  = 1;
    InstructionC  = 2;
}

message Value 
{
	bool   b = 1;
}

message Expression
{
    repeated Instructions code	= 1 [packed=true];
	repeated Value data			= 2 [packed=false];
}
```

... then the code is generated properly with a `case 10:` in the switch statement and code to handle the packing:

```swift
      override public func mergeFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Test.Expression.Builder {
        let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(copyFrom:self.unknownFields)
        while (true) {
          let protobufTag = try codedInputStream.readTag()
          switch protobufTag {
          case 0: 
            self.unknownFields = try unknownFieldsBuilder.build()
            return self

          case 10:
            let length = Int(try codedInputStream.readRawVarint32())
            let oldLimit = try codedInputStream.pushLimit(byteLimit: length)
            while codedInputStream.bytesUntilLimit() > 0 {
            let valueIntcode = try codedInputStream.readEnum()
            if let enumscode = Test.Instructions(rawValue:valueIntcode) {
                 builderResult.code.append(enumscode)
            } else {
                 _ = try unknownFieldsBuilder.mergeVarintField(fieldNumber: 1, value:Int64(valueIntcode))
            }
            }
            codedInputStream.popLimit(oldLimit: oldLimit)
```

So, my problem is that my client's server is treating the Protobuf v3 files as if packing is implied on eligible (primitive type) repeating items, but protobuf-swift is treating it as if packing is implied off and generating code that breaks when it encounters the packed data, interpreting it as unrecognized bytes.

IMHO the bug here is that protobuf-swift needs to assume `packed=true` when processing repeated primitive types in Protobuf v3 files.

Coming back to Google's statement...

> Protocol buffer parsers must be able to parse repeated fields that were compiled as packed as if they were not packed, and vice versa.

... it would seem that having to respect this statement in the docs this would seriously complicate the code generator, as it would have to detect and handle both scenarios regardless of whether packing is explicitly declared as on or off. I'd be happy if protobuf-swift simply assumed packed=true where applicable when processing Protobuf v3 files.

**Comment by gmckenzi** [comment]
Thank you for responding to this so quickly.
Does this need to be merged back to the ProtoBuf3.0-Swift3.0 branch?

**Comment by alexeyxo** [comment]
No, you can use master branch.
