### ISSUE TITLE
Swift 3 is working?

### ISSUE THREAD

**Issue by astoeckley** [alexeyxo/protobuf-swift#180]
#### Description

You have a recent commit that says you updated to Swift 3 syntax. However, when I use the most recent master branch in a project, Xcode 8 wants to migrate this Pod and claims there is a lot of legacy syntax. Is Swift 3 support complete?

**Comment by alexeyxo** [comment]
Swift 3.0 completely supported. You should update compiler and framework.

**Comment by astoeckley** [comment]
When I followed the instructions here:

https://github.com/alexeyxo/protobuf-swift#how-to-install-protobuf-compiler

It installed protobuf 2.6.1, is this correct? I thought your recent release requires protobuf 3. Is there something extra needed in these instructions to get the right version?

**Comment by astoeckley** [comment]
I'm not sure if this is because I have protoc 2.6.1 but attached is the kind of incompatibility that Xcode is reporting.

<img width="578" alt="screen shot 2016-09-16 at 14 00 39" src="https://cloud.githubusercontent.com/assets/4611759/18585347/b14cdd22-7c16-11e6-861f-7c45bfbacd4d.png">

**Comment by alexeyxo** [comment]
Protoc 2.6.1 not be supported in the future. Last updates you can see in https://github.com/alexeyxo/protobuf-swift/tree/Protobuf2.6-Swift3.0

You should install ProtocolBuffers 3.0.2.

**Comment by astoeckley** [comment]
If your master branch requires protobuf 3, shouldn't the instructions indicate how to get it? The ```brew install protobuf``` only installs 2.6. The Google page for protobufs shows several versions, none of which are swift. Do I use the Objective C one, and then build it myself, is that the best way to get Protobuf 3?

https://github.com/google/protobuf

**Comment by astoeckley** [comment]
It looks like my homebrew was out of date, a reinstall of that updated the protobuf to 3 upon reinstalling protobuf also. I will report back here with any additional problem.

**Comment by RanjaniOS** [comment]
alexeyxo
 can you help me out for protobuf2.6,swift 3.0, what is the  version no for this branch i should specify in pod specs as in our pod dependency is with your protocol buffer version.
"s.dependency 'ProtocolBuffers-Swift', '~>3.0.1'"
i am geting error by specifying this verson for "protobuf2.6,swift 3.0,"
