### ISSUE TITLE
No support for projects below Swift 3

### ISSUE THREAD

**Issue by Daredevll** [alexeyxo/protobuf-swift#183]
You could upload the older versions to Homebrew to make it a lot easier to install a Swift 2.2 compatible versions for older projects that are not yet migrated to Swift 3 syntax

**Comment by alexeyxo** [comment]
At the moment, Homebrew automatically uploading formula from git repositories. Google uploaded protobuf 3.0 in homebrew, but oldest versions protobuf-swift not supporting.
You can manually install oldest versions.
