### ISSUE TITLE
JSONSerialization crash

### ISSUE THREAD

**Issue by alkozin** [alexeyxo/protobuf-swift#184]
#### Description

`JSONSerialization.data` crashes when I try to call `.toJSON()` after build object.

Looks like `UInt32` values is setted to Dictionary but serializer can't parce it and crash with message:
"Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (_SwiftValue)'"

When I change `encode()` method to set NSNumber instead of UInt32 to Dictionary all it's ok.

**Comment by alexeyxo** [comment]
You can testing last commit.

**Comment by alkozin** [comment]
Thanks!
