### ISSUE TITLE
Swift 3.0 support question

### ISSUE THREAD

**Issue by irahan888** [alexeyxo/protobuf-swift#185]
Hi, I'm new to this ProtocolBuf Swift project. 
I think I've updated all the tools to latest version(home-brew, cocoapods, ProtoBuf...), but still I will get the conflict syntax err w/ Swift 3.0 on Xcode, could you please help me to on this?
<img width="430" alt="2016-09-23 1 00 40" src="https://cloud.githubusercontent.com/assets/22363199/18774851/b8d10fa4-818f-11e6-813d-b9e4f0910a4a.png">

my Pods install using latest protobuf
<img width="688" alt="2016-09-23 1 13 20" src="https://cloud.githubusercontent.com/assets/22363199/18774836/8c72c178-818f-11e6-9234-4d1935526eec.png">
Podfile:
<img width="316" alt="2016-09-23 1 15 07" src="https://cloud.githubusercontent.com/assets/22363199/18774856/cc8f5c8a-818f-11e6-9ef8-e5bcb256ebb9.png">

brew already installed latest protobuf
<img width="505" alt="2016-09-23 1 17 09" src="https://cloud.githubusercontent.com/assets/22363199/18774892/13924548-8190-11e6-85a9-8ed959c9d545.png">

proto.swift file are also generated by latest compiler
by the way, got this no such module issue also, not sure if it's related to syntax conflict issue
<img width="642" alt="2016-09-23 1 22 33" src="https://cloud.githubusercontent.com/assets/22363199/18774989/018c3218-8191-11e6-8afa-e6d5dbc6f9d2.png">

**Comment by alexeyxo** [comment]
What version of cocoapods are you using?

**Comment by irahan888** [comment]
pod --version
1.0.1

**Comment by alexeyxo** [comment]
Cocoapods versions of 1.0.1 not supporting Swift.3.0. You should use version 1.1.0.rc.2. 
```
sudo gem install cocoapods --pre
```

**Comment by irahan888** [comment]
thanks for reply, I've tried update cocoapods, and that's worked!
one more question, is this also workable by using Carthage?

**Comment by alexeyxo** [comment]
I think, carthage supports Siwft 3.0.
