### ISSUE TITLE
Swift 3.0 compiler error

### ISSUE THREAD

**Issue by lzc1104** [alexeyxo/protobuf-swift#188]
#### ```.proto``` file to reproduce
```protobuf

```

#### Description

I cloned the branch protobuf-swift-ProtoBuf3.0-Swift3.0 and run ./scripts/build.sh
but resulted in the error:
    This file was generated by an older version of protoc which is incompatible with your Protocol Buffer headers. Please regenerate this file with a newer version of protoc.
    I have update the libprotoc to latest version as shown above , could you offer me a solution or some ideas? Thanks you

**Comment by alexeyxo** [comment]
You should use master branch.

**Comment by lzc1104** [comment]
But when I compiled the .proto files the .pb.swift files ends up in Swift 2 syntax , I want the version of Swift 3 , can you give me some suggestion?

**Comment by alexeyxo** [comment]
You need reinstall protobuf-swift compiler. how you installed him erly, from homebrew?

**Comment by lzc1104** [comment]
Yes, I have red some issues related to  that and find out that install through homebrew is not worked since it have no version of Swift3 , so I have uninstall it and reinstall

The good news is I suddenly found that Xcode have not complained the syntax yet , may be  something wrong before but I did not figure out

Thanks for your patience
