### ISSUE TITLE
JSON to ProtoBuf

### ISSUE THREAD

**Issue by shizambles** [alexeyxo/protobuf-swift#189]
#### ```.proto``` file to reproduce
```protobuf

```

#### Description
Hi,
    I have a potential problem with de-serialising JSON messages to Protobuf. Consider a protobuf message as below.
`message ProfilesProto {
    required int64 lastModifiedTime = 1;
    repeated string userIds = 10;
}`

Suppose I use the `encode` method to create a `Dictionary<String,Any>` and then convert that dictionary to a JSON string (which works fine). Now when I try to do the opposite first by reading the JSON via `JSONSerialization.jsonObject(with: data, options: .mutableContainers) as? [String:AnyObject]` and the use the `encode` method, the `encode` method fails since it tries to cast the `lastModifiedTime` to an Int64.

`if let jsonValueLastModifiedTime = jsonMap["lastModifiedTime"] as? Int64 {
        resultDecodedBuilder.lastModifiedTime = jsonValueLastModifiedTime
      }`

Any suggestions on how to overcome this?

Regards
S

**Comment by alexeyxo** [comment]
I think, you are using old version of compiler and library. Your example currently has a code as:
```swift
if let jsonValueLastModifiedTime = jsonMap["lastModifiedTime"] as? String {
        resultDecodedBuilder.lastModifiedTime = Int64(jsonValueLastModifiedTime)!
 }
```

**Comment by shizambles** [comment]
Yes indeed. You are right. This is no longer an issue. Thanks for the quick response!
