### ISSUE TITLE
Method does not override any method from its superclass

### ISSUE THREAD

**Issue by MuniekMg** [alexeyxo/protobuf-swift#190]
#### ```.proto``` file to reproduce
```protobuf

```

#### Description
I use syntax = "proto3";
I've just read about similar problem in here, but it doesn't solve my problem.
I used protobuf-swift pod, from variety od branches like master, iOS Only, protobuf3.0-swift3.0, and protobuf2.6-Swift.3.0 and using protoc 3.0.0 and 3.1.0 but always the same problem:

xxxx.proto.swift:221:34: Method does not override any method from its superclass
Potential overridden class method 'decodeToBuilder(jsonMap:)

Thanks in advance!

**Comment by alexeyxo** [comment]
You use oldest version protobuf-swift library.
