### ISSUE TITLE
Customizing

### ISSUE THREAD

**Issue by sm2017** [alexeyxo/protobuf-swift#192]
I want to fork your repository and change something , How can I do this

1- rename ```--swift_out``` to ``--prefix_out```
2- force compiler to add prefix to any property and message for example
compile following
```
syntax = "proto3";
message Person {
    int32 id = 1;
    string name = 2;
    string email = 3;
}
```
like
```
syntax = "proto3";
message PrefixPerson {
    int32 prefix_id = 1;
    string prefix_name = 2;
    string prefix_email = 3;
}
```

3-Customzing inheritance , for example if there is a property that is ```Person``` message it must be child of ```GeneratedPersonMessageProtocol``` instead of ```GeneratedMessageProtocol``` any other messages is child of  ```GeneratedMessageProtocol```
```
syntax = "proto3";
message Test{
    Person person= 1;
    int id =2
}
```

**Comment by alexeyxo** [comment]
You need reed Google ProtocolBuffers documentation.  The word "swift" or in your example "prefix", protoc get from name of plugin, for example "protoc-gen-swift". Prefix of message it is extension for file options.
