### ISSUE TITLE
Why not making it compatible with linux ?

### ISSUE THREAD

**Issue by hmazelier** [alexeyxo/protobuf-swift#196]
Hi,
As your only dependency is Foundation, is there a reason you didn't write it compatible with linux ? 
It could be very interesting as server side framework, next to `vapor, perfect, zewo`or else ...
Great job by the way & thanks

**Comment by alexeyxo** [comment]
Foundation has available on linux. Generated files are compiled on linux.
https://github.com/alexeyxo/protobuf-swift#how-to-install-protobuf-compiler-on-linuxubuntu-1404

**Comment by hmazelier** [comment]
Thank you ! 
But I meant why don't you write it compatible on linux in "Platforms" ? 
Also in awesome-swift :)
As it is !!

**Comment by alexeyxo** [comment]
Done.
