### ISSUE TITLE
Support of swift3?

### ISSUE THREAD

**Issue by vkanishk** [alexeyxo/protobuf-swift#198]
#### ```.proto``` file to reproduce
```protobuf

```

#### Description

Is support for swift3 available in latest protobuf?

I am trying to work on swift3 and want to use protobuf. Took latest code from "https://github.com/alexeyxo/protobuf-swift" but when running "./scripts/build.sh" i get this error. 

Making install in plugin/compiler
 ../.././install-sh -c -d '/usr/local/bin'
  /bin/sh ../../libtool   --mode=install /usr/bin/install -c protoc-gen-swift '/usr/local/bin'
libtool: install: /usr/bin/install -c protoc-gen-swift /usr/local/bin/protoc-gen-swift
make[2]: Nothing to be done for `install-data-am'.
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.

**Comment by alexeyxo** [comment]
You have a log without errors.

**Comment by vkanishk** [comment]
ok. i got it now. i thought there was some error. Now will the xcodeproj work with swift3?
