### ISSUE TITLE
int64 transformed to string for .encode()

### ISSUE THREAD

**Issue by cd24** [alexeyxo/protobuf-swift#201]
#### ```.proto``` file to reproduce
```protobuf
syntax = "proto3";
message myMessage {
  int64 my_int = 1;
}
```

#### Description
When using this tool, I expect for int64 fields to be represented as numbers in their json form (int64). In the same way that the component casts Double, I would expect that a declared Int64 field is cast as Int64, rather than wrapped in a string.

The produced file has 

```swift
jsonMap["myInt"] = "\(myInt)"
```

When i would expect
``` swift
jsonMap["myInt"] = myInt
```
I have confirmed that removing the quotes in the generated file does not produce errors for encoding, and creates the expected behavior.

**Comment by alexeyxo** [comment]
Hi! You are wrong. In official google specification ```Int64/Fixed64/UInt64``` in json has represented as ```String```.
[JSON Mapping](https://developers.google.com/protocol-buffers/docs/proto3?hl=ru#json)
