### ISSUE TITLE
for Int64, decodeToBuilder() only accepts String and refuse numbers (google spec allows them)

### ISSUE THREAD

**Issue by Nicien** [alexeyxo/protobuf-swift#202]
#### ```.proto``` file to reproduce
```
syntax = "proto3";
message TestObject {
  int64 id = 1;
}
```

#### `.json` file to reproduce
```
{
  "id" : 42
}
```

#### Result:
`testObject.id = 0`

#### Excepted result
`testObject.id = 42`

#### Description
The generated function ```decodeToBuilder(jsonMap:Dictionary<String,Any>) throws``` except a `String` and nothing else (Int)
```
if let jsonValueId = jsonMap["id"] as? String {
    resultDecodedBuilder.id = Int64(jsonValueId)!
}
```

I except protobuf-swift to accept both format `42` and `"42"` because the [document](https://developers.google.com/protocol-buffers/docs/proto3?hl=ru#json) specifies: `Either numbers or strings are accepted.` for int64 values.

What do you thing about adding Int support ?
```
 if let jsonValueId = jsonMap["id"] {
    if let jsonValueId = jsonValueId as? String {
        resultDecodedBuilder.id = Int64(jsonValueId)!
    } else if let jsonValueId = jsonValueId as? Int64 {
        resultDecodedBuilder.id = Int64(jsonValueId)
    }
}
```

The same problem will arise for the `int32`, `fixed32`, `uint32`

**Comment by alexeyxo** [comment]
Done.

**Comment by Nicien** [comment]
thank you very much for the update :)
