### ISSUE TITLE
invalidProtocolBuffer "Truncated Message"

### ISSUE THREAD

**Issue by anuragedushire** [alexeyxo/protobuf-swift#204]
#### Version of protoc (```protoc --version```)
3.1.0

#### Version of ProtocolBuffers.framework
3.0.6

#### Description

I have a protocol buffer UserDataProto which occasionally throws exception at the following code -

let userBuilder = UserDataProto.Builder()
//
// Do other stuff
//
let userData = try! userBuilder.build()
let data = userData.data()
let builder = UserDataProto.Builder()
try! builder.mergeFrom(data: data)  <-- crashes here

I thought this should 'never' happen, as I am merging something from the same type. The error says invalidProtocolBuffer "Truncated Message". Is this a bug in the library? Or, this can really happen because I am doing something odd with the protobuf in "// Do other stuff"?

Note: All the fields in the protobuf are either optional or repeated, in case that matters.

**Comment by alexeyxo** [comment]
I should to view the .proto file and what do you set in fields.

**Comment by anuragedushire** [comment]
The protocol buffer is huge, if I consider the nested/embedded types. 

message UserDataProto {
  optional int32 level = 1;
  optional int32 activity = 2;
  optional int32 dscore = 3;
  optional int32 sscore = 6;

  optional int64 l_prompt = 8;
  optional int32 ltt_score = 9;
  repeated string seen_id = 10;
  optional int32 score_at_ltr = 11;
  optional int32 num_ptr = 12;
  optional int64 ltf_uptime = 13;

  repeated TaskScore task_score = 14;
  repeated GameScore g_score = 15;

  optional int32 rank = 16;

  repeated Table table = 17;  
  repeated ColumnValue cv = 18;
}

message TaskScore {
  optional int32 level = 1;
  optional int32 task = 2;
  optional int32 score = 3;

  optional int32 appversion = 4;
  optional int64 ftime = 5;
}

message GameScore {
  optional string qid = 1;
  optional int32 score = 2;
  optional string gs_id = 3;
  optional int32 index = 4;
}

message ColumnValue {
  optional string name = 1;
  optional string string_value = 2;
  optional int64 int64_value = 3;
  optional bytes byte_array_value = 4;
}
message TableRow {
  optional string row_id = 1;
  repeated ColumnValue cv = 2;
}
message Table {
  optional string table_name = 1;
  repeated TableRow row = 2;
}


Since there are various fields and different things get set at different places. I can't put all the values that I set here. Any pointer to which fields might be the suspects?

**Comment by anuragedushire** [comment]
Has this been fixed?
