### ISSUE TITLE
Cannot load underlying module for 'XCTest'? And How to use pod with one branch?

### ISSUE THREAD

**Issue by whoooami** [alexeyxo/protobuf-swift#209]
#### ```.proto``` file to reproduce
```protobuf

```

#### Description
protobuf-swift/plugin/ProtocolBuffers/ProtocolBuffersTests/ErrorHandlingTest.swift:9:8: Cannot load underlying module for 'XCTest'

another question:
How to use pod with branch? like this?
pod 'ProtocolBuffers-Swift', :git => 'https://github.com/alexeyxo/protobuf-swift', :branch => 'ProtoBuf3.0-Swift3.0'

Thanks.

**Comment by alexeyxo** [comment]
pod 'ProtocolBuffers-Swift'
