### ISSUE TITLE
mergeFrom doesn't merge fields from other object

### ISSUE THREAD

**Issue by mhahn** [alexeyxo/protobuf-swift#22]
https://github.com/alexeyxo/protobuf-swift/blob/master/src/compiler/swift_message.cc#L774-L776

given the function definition, i would expect this function to copy the fields for the "other" protobuf that is passed in.

why does it check if its the same class and then return itself? it should be the same class and then copy the attributes.

**Comment by alexeyxo** [comment]
If ```other``` is the default instance, we know none of its fields are set so we can skip the merge.

**Comment by mhahn** [comment]
![image](https://cloud.githubusercontent.com/assets/704593/5723822/f10fc10c-9afb-11e4-95cc-35872d7a7199.png)

you can see above that its not merging the contents from the other protobuf because a populated protobuf is always equal to the default instance.

i removed the return statement in mergeFrom and it works properly.

**Comment by alexeyxo** [comment]
You are trying to merge two of the same object "other",this is not true.
In this case, the "other" object have hasn't established fields.
You can merge other and user, because "user" has established field. 
You can look implementation in C ++ / Java.

**Comment by mhahn** [comment]
sorry, i had a typo in there. this shows that other and user don't merge properly:

![image](https://cloud.githubusercontent.com/assets/704593/5725040/8fc79d8a-9b04-11e4-8786-77c00544e612.png)

**Comment by mhahn** [comment]
because `user == UserService.Containers.user()` they don't merge.

**Comment by alexeyxo** [comment]
```protobuf
message Test
{
  optional string str = 11;
}

```

```swift
        var builder = Test.builder()
        builder.str = "123"
        println(builder)
        var build = builder.build()
        println(build)
        var builder2 = Test.builder()
        builder2.mergeFrom(build)
        var build2 = builder2.build()

        println(build2)
        println(build2 == build)
        println(build2 == Test.builder().build())
        println(build == Test.builder().build())
        println(build == Test())
```

Log:
```
 str: 123 

 str: 123 

 str: 123 

 str: 123 

true
false
false
false
```
All ok!!
