### ISSUE TITLE
Optional binding on non-optional

### ISSUE THREAD

**Issue by Ramshandilya** [alexeyxo/protobuf-swift#221]
https://github.com/alexeyxo/protobuf-swift/blob/1753af00ef0d8f34cab8ab67067945b474b80fcc/Source/Google.Protobuf.Struct.proto.swift#L605

`keyFields` is of type `String`. So `guard` statement breaks, since the result is not an optional.

**Comment by Ramshandilya** [comment]
I think this is my Xcode 9 complaining in Swift 4.0 project? 
Shouldn't swift 4.0 & 3.2 co-exist?

**Comment by key3board** [comment]
Xcode9 run failed in my project

**Comment by iain17** [comment]
Upgrade to the latest protobuf swift.
brew upgrade protobuf-swift

and make sure to use the new swift4 branch:
pod 'ProtocolBuffers-Swift', :git => 'https://github.com/alexeyxo/protobuf-swift.git', :branch => 'swift4'

That's what fixed it for me. After regenerating the swift file from my .proto file and doing a pod install
