### ISSUE TITLE
failed run in xcode9

### ISSUE THREAD

**Issue by key3board** [alexeyxo/protobuf-swift#222]
#### ```.proto``` file to reproduce
```protobuf

```

**Comment by alexeyxo** [comment]
https://forums.developer.apple.com/thread/71124

**Comment by KompoD** [comment]
It doesn't help 🙁

**Comment by key3board** [comment]
xcode 9    

error   in  the  Google.Protobuf.Descriptor.proto.swift

Type 'Google.Protobuf.FieldDescriptorProto.Type' has no member 'typeDouble'
   
Non-nominal type 'Google.Protobuf.FieldDescriptorProto.Type' does not support explicit initialization

Type 'Google.Protobuf.FieldDescriptorProto.Type' has no member 'fromString'

how to fix  this  issues   thank you  for your  response

**Comment by key3board** [comment]
https://github.com/alexeyxo/protobuf-swift/issues/213
