### ISSUE TITLE
Xcode 9 failure. "Use of unresolved identifier"

### ISSUE THREAD

**Issue by KompoD** [alexeyxo/protobuf-swift#223]
#### ```.proto``` file to reproduce
```protobuf
syntax = "proto3";

message BaseModelRequestProtobufDTO {
    string name = 1;
    string model = 2;
}

message BaseModelResponseProtobufDTO {
    string response = 1;
}
```

#### Description
I have "Use of unresolved identifier 'BaseModelResponseProtobufDto'" when try to build app.
Can you help me?
![2017-09-29 10 40 37](https://user-images.githubusercontent.com/14116289/31005839-155ac084-a503-11e7-9a49-391f518b2c00.png)
Answer of #213 issue doesn't help me :(

**Comment by svyatoslav-reshetnikov** [comment]
Hi, I have the same thing. How can I resolve it?

**Comment by KompoD** [comment]
Sorry!
Problem was in my project.
Proto-file didn't mark itself as target of my project :)
