### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by J-cyz** [alexeyxo/protobuf-swift#225]
#### Version of Swift
	xcode 9.0
#### Description
It can compile success by download demo,but when I install protocolbuffer-swift from Pod and compile, 
I got 24 error in the three file :
	1.Google.Protobuf.Struct.proto.swift
		initilizar for conditional binding must have Optional type,not 'String';
	2.Google.Protobuf.Type.proto.swift
		Type 'Google.Protobuf.Type' has no member 'classBuilder';
		Type 'Google.Protobuf.Type' has no member 'Builder';
		Type 'Google.Protobuf.Type' has no member 'builderWithPrototype';
		Non-nominal type 'Google.Protobuf.Type' does not support explicit initialization;
	3.Google.Protobuf.Descriptor.proto.swift
		Type 'Google/Protobuf.FieldDescriptorProto.Type' has no member 'typeDouble';
		Non-nominal type 'Google.Protobuf.FieldDescriptorProto.Type' does not support explicit initialization;
		Type 'Google.Protobuf.FieldDescriptorProto.Type' has no member 'fromString';

How to fix it ?

**Comment by One1Light** [comment]
Type 'Google.Protobuf.Type' has no member 'Builder'

**Comment by One1Light** [comment]
how fix it

**Comment by KompoD** [comment]
Try this solution #213
