### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by wzpziyi1** [alexeyxo/protobuf-swift#227]
###### 3.5.0

Xcode 9.0

When I run  . / scripts/build. Sh , appear the following error:

In file included from swift_generator.cc:22:
./google/protobuf/descriptor.pb.h:17:2: error: This file was generated by an
      older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:18:2: error: incompatible with your Protocol
      Buffer headers. Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
./google/protobuf/descriptor.pb.h:19:2: error: regenerate this file with a newer
      version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
In file included from swift_file.cc:23:
./google/protobuf/descriptor.pb.h:17:2: error: This file was generated by an
      older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:18:2: error: incompatible with your Protocol
      Buffer headers. Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
./google/protobuf/descriptor.pb.h:19:2: error: regenerate this file with a newer
      version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
depbase=`echo swift_primitive_field.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	g++ -DHAVE_CONFIG_H -I. -I../..     -I/usr/local/include -MT swift_primitive_field.o -MD -MP -MF $depbase.Tpo -c -o swift_primitive_field.o swift_primitive_field.cc &&\
	mv -f $depbase.Tpo $depbase.Po
In file included from swift_oneof.cc:24:
./google/protobuf/descriptor.pb.h:17:2: error: This file was generated by an
      older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:18:2: error: incompatible with your Protocol
      Buffer headers. Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
./google/protobuf/descriptor.pb.h:19:2: error: regenerate this file with a newer
      version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
In file included from swift_enum.cc:24:
./google/protobuf/descriptor.pb.h:17:2: error: This file was generated by an
      older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:18:2: error: incompatible with your Protocol
      Buffer headers. Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
./google/protobuf/descriptor.pb.h:19:2: error: regenerate this file with a newer
      version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
In file included from swift_enum_field.cc:28:
In file included from ./swift_helpers.h:23:
./google/protobuf/descriptor.pb.h:17:2: error: This file was generated by an
      older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:18:2: error: incompatible with your Protocol
      Buffer headers. Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
./google/protobuf/descriptor.pb.h:19:2: error: regenerate this file with a newer
      version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
In file included from swift_message_field.cc:27:
In file included from ./swift_helpers.h:23:
./google/protobuf/descriptor.pb.h:17:2: error: This file was generated by an
      older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:18:2: error: incompatible with your Protocol
      Buffer headers. Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
./google/protobuf/descriptor.pb.h:19:2: error: regenerate this file with a newer
      version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
In file included from swift_map_field.cc:30:
In file included from ./swift_helpers.h:23:
./google/protobuf/descriptor.pb.h:17:2: error: This file was generated by an
      older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:18:2: error: incompatible with your Protocol
      Buffer headers. Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
./google/protobuf/descriptor.pb.h:19:2: error: regenerate this file with a newer
      version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
3 errors generated.
make[2]: *** [swift_oneof.o] Error 1
make[2]: *** Waiting for unfinished jobs....
3 errors generated.
3 errors generated.
make[2]: *** [swift_enum.o] Error 1
make[2]: *** [swift_enum_field.o] Error 1
3 errors generated.
3 errors generated.
3 errors generated.
make[2]: *** [swift_map_field.o] Error 1
make[2]: *** [swift_message_field.o] Error 1
make[2]: *** [swift_generator.o] Error 1
3 errors generated.
make[2]: *** [swift_file.o] Error 1
In file included from swift_primitive_field.cc:30:
In file included from ./swift_helpers.h:23:
./google/protobuf/descriptor.pb.h:17:2: error: This file was generated by an
      older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:18:2: error: incompatible with your Protocol
      Buffer headers. Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
./google/protobuf/descriptor.pb.h:19:2: error: regenerate this file with a newer
      version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
3 errors generated.
make[2]: *** [swift_primitive_field.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by alexeyxo** [comment]
Done.
