### ISSUE TITLE
Generated json keys don't have the same case as their proto fields.

### ISSUE THREAD

**Issue by tevjef** [alexeyxo/protobuf-swift#229]
#### Version of protoc (```protoc --version```)
libprotoc 3.4.0
#### ```.proto``` file to reproduce
```protobuf
syntax = "proto2";
message Person {
    required int32 id = 1;
    required string first_name = 2;
    required string last_name = 3;
    optional string email = 4;
}
```

#### What I found

The json encoding and decoding uses camelCase keys despite the protobuf fields being snake_cased. 

```swift
if hasFirstName {
    jsonMap["firstName"] = firstName
}
if hasLastName {
    jsonMap["lastName"] = lastName
}
```
#### What I expect

I expected the json fields to use the same case their corresponding fields in the protobuf file. 

```swift
if hasFirstName {
    jsonMap["first_name"] = firstName
}
if hasLastName {
    jsonMap["last_name"] = lastName
}
```

https://developers.google.com/protocol-buffers/docs/style

**Comment by alexeyxo** [comment]
I looked [Protobuf](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf) documentation and founded this example:
```protobuf
package google.profile;
message Person {
  string first_name = 1;
  string last_name = 2;
}

{
  "@type": "type.googleapis.com/google.profile.Person",
  "firstName": <string>,
  "lastName": <string>
}
```
I use to standart methods for get json field name, without transformations:
```c++
descriptor->json_name();
```
