### ISSUE TITLE
Error in Xcode10

### ISSUE THREAD

**Issue by icefox57** [alexeyxo/protobuf-swift#236]
#### Version of protoc (```protoc --version```)
    pod 'ProtocolBuffers-Swift', '~> 4.0.1'

Get compiler error in Xcode10 swift 4.1

#### Description
![image](https://user-images.githubusercontent.com/1716737/41403690-0f136c9c-6ff8-11e8-932f-15c7959e337b.png)

**Comment by alexeyxo** [comment]
Done.
