### ISSUE TITLE
Build fails with protobuf 3.6.0

### ISSUE THREAD

**Issue by ilovezfs** [alexeyxo/protobuf-swift#237]
Full build log:
https://gist.github.com/ilovezfs/cdd92f4a563db1677562095c3973e0c6

CC @alexeyxo

**Comment by alexeyxo** [comment]
Done.

**Comment by ilovezfs** [comment]
@alexeyxo perfect. I have included it with https://github.com/Homebrew/homebrew-core/pull/29239
