### ISSUE TITLE
XCode 10/swift 4.2 compilation errors

### ISSUE THREAD

**Issue by volodg** [alexeyxo/protobuf-swift#239]
#### Description
Can not compile `ProtocolBuffers-Swift` pod dependency with XCode 10

**Comment by gregoireLem** [comment]
Same here : using Xcode 10 beta 5
![capture d ecran 2018-08-20 a 17 37 28](https://user-images.githubusercontent.com/31652880/44350483-c532db80-a49f-11e8-8f69-757664505bb2.png)

**Comment by gregoireLem** [comment]
@volodg how did you managed it ?

**Comment by gregoireLem** [comment]
Same here

**Comment by joejune** [comment]
@alexeyxo: `master` still fails to build in the Xcode 10 GM seed.  Please merge the trivial fix in #241 to resolve this issue.  I'd really like to avoid switching my Cartfile to use a fork.  Thanks!

**Comment by joejune** [comment]
Fixed in https://github.com/alexeyxo/protobuf-swift/commit/108d32b8d4d520e0a1394a0108f4c3e0d37a9e99#diff-37a034536038eb889e89f162e83cd6b2L483
