### ISSUE TITLE
Build error on Xcode beta 5

### ISSUE THREAD

**Issue by gregoireLem** [alexeyxo/protobuf-swift#240]
I have this error after upgrading to Xcode beta : 
ProtocolBuffers-Swift (4.0.4)
![capture d ecran 2018-08-20 a 18 23 11](https://user-images.githubusercontent.com/31652880/44353182-92d8ac80-a4a6-11e8-945d-537d57dcd955.png)

**Comment by volodg** [comment]
Duplicates - https://github.com/alexeyxo/protobuf-swift/issues/239

**Comment by joejune** [comment]
Fixed in https://github.com/alexeyxo/protobuf-swift/commit/108d32b8d4d520e0a1394a0108f4c3e0d37a9e99#diff-37a034536038eb889e89f162e83cd6b2L483
