### ISSUE TITLE
UnsafeRawPointer(&buffer+bufferPos)   Ambiguous use of 'init'

### ISSUE THREAD

**Issue by fangnengyan** [alexeyxo/protobuf-swift#243]
#### ```.proto``` file to reproduce
```protobuf

```

**Comment by fangnengyan** [comment]
Ambiguous use of 'init'

**Comment by git-john** [comment]
so do i, how to resolve it?

**Comment by git-john** [comment]
我也是，你怎么解决的？

**Comment by RanjaniOS** [comment]
Same issue i am gettin using protobuf version 3.0.0 .Could any one help me out for this .
