### ISSUE TITLE
Namespace Collision between protobuf-objc & protobuf-swift

### ISSUE THREAD

**Issue by JustinDSN** [alexeyxo/protobuf-swift#25]
There is a namespace collision when you attempt to use both protobuf-objc & protobuf-swift in the same project.  Both are attempting to use ```ProtocolBuffers```.

**Comment by alexeyxo** [comment]
I'm sorry, but I did not think about use two libraries at ones of one project. This is a very exceptional situation... Most likely it is not possible...

**Comment by JustinDSN** [comment]
So is the ProtocolBuffers-Swift meant to be a drop in replacement for ProtocolBuffers-Obj.  With minor refactoring?  what's the future upgrade story going to look like?
