### ISSUE TITLE
Xcode 12.0 BETA 4

### ISSUE THREAD

**Issue by gregoireLem** [alexeyxo/protobuf-swift#257]
#### Description

Getting this error when compiling after upgrading to Xcode 12.0 beta 4 :
**Generic parameter 'Element' could not be inferred**

on lines `memcpy(&bytes, &buffer + bufferPos, pos)` in CodedInputStream.swift

![Capture d’écran 2020-08-11 à 17 33 55](https://user-images.githubusercontent.com/31652880/89917273-e47d2300-dbf8-11ea-8e05-b23829a49ce5.png)

Thanks for helping

**Comment by impresyjna** [comment]
Hi, 
How did you fix this issue?

**Comment by gregoireLem** [comment]
By switching to apple repo https://github.com/apple/swift-protobuf ;)

**Comment by impresyjna** [comment]
Thanks :)

**Comment by Ger-Teunis-52DN** [comment]
I've made a pull request which fixes the issue. I saw somebody else also made same patch so I made a pull request using their patch instead.

**Comment by 51wiki** [comment]
When I upgraded Xcode to Version 12.2, I encountered the same error. How did I fix it?
