### ISSUE TITLE
Generic Response Object Serialization

### ISSUE THREAD

**Issue by JustinDSN** [alexeyxo/protobuf-swift#26]
I'm attempting to create a ['Generic Response Object Serialization'](https://github.com/Alamofire/Alamofire#generic-response-object-serialization) deserializer for Alamofire.

Because there is no common protocol that generated messages implement, I tried to use the type specification of ```GeneratedMessageBuilder```.  However, the code blows up [here](https://github.com/alexeyxo/protobuf-swift/blob/1540f4c1771d426ff2ee5c223ea46db986a73913/src/ProtocolBuffers/runtime-pb-swift/GeneratedMessage.swift#L61).

This is an example of the serializer I tried to implement.
```
extension Alamofire.Request {
    public func responseProtocolBuffer<T: GeneratedMessageBuilder>(completionHandler: (NSURLRequest, NSHTTPURLResponse?, T?, NSError?) -> Void) -> Self {
        let serializer: Serializer = { (request, response, data) in
            if response != nil && data != nil {
                let returnValue = T().mergeFromData(data!)
                
                return (returnValue, nil)
            } else {
                return (nil, nil)
            }
        }
        
        return response(serializer: serializer, completionHandler: { (request, response, object, error) in
            completionHandler(request, response, object as? T, error)
        })
    }
}
```

I think the ultimate solution is to have a ```GenerateMessageProtocol```, that all generated messages adhere to.  Perhaps something like:

```
protocol GenerateMessageProtocol {
    class func parseFromData(data:NSData) -> self
    //etc.
}
```

And then GeneratedMessages could look like: 
```
final internal class CPBVersion : GeneratedMessage, GenerateMessageProtocol {
   //xxx
}
```

**Comment by alexeyxo** [comment]
Ok! I am agree!

**Comment by JustinDSN** [comment]
If we can't use Swift Protocol Buffers at the same time, and ***if*** it's not a drop in replacement for Objective C then we'll want a similar implementation of the protocol idea in Objective C.

**Comment by alexeyxo** [comment]
Done.
