### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by GlassAndOneHalf** [alexeyxo/protobuf-swift#27]
Are there any plans to support [Carthage](https://github.com/Carthage/Carthage) in future versions? It would be incredibly useful.

**Comment by alexeyxo** [comment]
Hi! I'll add the support Carthage soon.

**Comment by alexeyxo** [comment]
I added support for Carthage, but so far only for iOS. I don't have OSX Developer Program.

Cartfile:
```
github "alexeyxo/protobuf-swift" "carthage"
```

**Comment by alexeyxo** [comment]
At now works of "master" and all targets.
