### ISSUE TITLE
Unable to compile generated swift code with error message "classBuilder() does not override any method from super class"

### ISSUE THREAD

**Issue by wentao** [alexeyxo/protobuf-swift#34]
Here is my protobuf code

message Message {
  extensions 100 to max;
}

message Connect {
  extend Message {
    optional Connect connect = 100;
  }
  optional int64 latest_id = 1 [ default = 0 ];
}

and the following methods are marked with this error message

  internal override class func classBuilder() -> MessageBuilder {
    return ConnectBuilder()
  }
  internal override func classBuilder() -> MessageBuilder {
    return Connect.builder()

**Comment by alexeyxo** [comment]
Try it:
```protobuf
message ChatMessage {
  extensions 100 to max;
}

message Connect {
  extend ChatMessage {
    optional Connect connect = 100;
  }
  optional int64 latest_id = 1 [ default = 0 ];
}
```
The problem arises because of the reserved name "Message"

**Comment by wentao** [comment]
Oh right, it works now, thanks!
