### ISSUE TITLE
Use parseFromData Failure

### ISSUE THREAD

**Issue by zhouzizi** [alexeyxo/protobuf-swift#35]
I got NSData from urlrequest, and can print the data's content ,but when i convert NSData use parseFromData ,like   var classls = ClassList.parseFromData(data) ，it print the error at the void :parseFromData ,  fatal error: unexpectedly found nil while unwrapping an Optional value . How can i fix the error?

**Comment by alexeyxo** [comment]
You send or receive not true binary data.

**Comment by zhouzizi** [comment]
let data = responseObject as NSData
 let bytes:UnsafePointer<Void> = data.bytes
 let str = NSString(bytes: bytes, length: data.length, encoding: NSUTF8StringEncoding)

data value is not nil ,bytes value is not nil too, data.length value is 1k+, but   str is nil..
