### ISSUE TITLE
Build.sh error

### ISSUE THREAD

**Issue by GianiVersace** [alexeyxo/protobuf-swift#39]
It says this : 
checking google/protobuf/stubs/common.h usability... no
checking google/protobuf/stubs/common.h presence... no
checking for google/protobuf/stubs/common.h... no
configure: error: 
ERROR: protobuf headers are required.

You must either install protobuf from google,
or if you have it installed in a custom location
you must add '-Iincludedir' to CXXFLAGS
and '-Llibdir' to LDFLAGS.

If you did not specify a prefix when installing
protobuf, try
  './configure CXXFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib'
In some 64-bit environments, try LDFLAGS=-L/usr/local/lib64.

i downloaded the zip , extracted it to desktop.

Can you please help me?

**Comment by alexeyxo** [comment]
try this:

```./configure CXXFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib```
or 
```./configure CXXFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib64```

```make && make install```

**Comment by GianiVersace** [comment]
neither of the ./configure worked.
What's up with make && make install?
sorry but i'm kind of a newbie.
I need protobuf so i can send protobuf objects as binary through sockets on iOS.
I've managed to set it up for obj-c, but unfortunately, there is no support for binary transfer yet, regardless of the socket API.
But i found some socket API which supports binary transfer (i hope it's gonna do it's job...) and that's why i'm trying now to set up the protobuf-swift compiler.

**Comment by GianiVersace** [comment]
i tried to install it with carthage too and i get:
*** Fetching protobuf-swift
*** Checking out protobuf-swift at "1.4.1"
*** xcodebuild output can be found in /var/folders/41/_byf2r1d217_yvn9m2hvtml80000gq/T/carthage-xcodebuild.7X5QGW.log
*** Building scheme "ProtocolBuffers" in ProtocolBuffers.xcodeproj
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

I created a file named Cartfile.txt, saved it into my project's directory, put this github "alexeyxo/protobuf-swift" in it. I cd'ed to my project's directory, ran carthage update and got the error that i've copy/pasted above. Thanks in advance

**Comment by alexeyxo** [comment]
```make && make install``` - this command builds the protobuf-swift compiler.
PB - protocol serialization and deserialization of data.  What kind to use the data transfer protocols - you have to define themselves.

I can not reproduce your problem:
```
$ carthage update
*** Fetching protobuf-swift
*** Checking out protobuf-swift at "1.4.1"
*** xcodebuild output can be found in /var/folders/v_/6_w011sn2vg6b87sr0zplrzw0000gn/T/carthage-xcodebuild.oIKYu5.log
*** Building scheme "ProtocolBuffers" in ProtocolBuffers.xcodeproj
*** Building scheme "ProtocolBuffers(OSX)" in ProtocolBuffers.xcodeproj
```
What kind of version Xcode you use?

**Comment by GianiVersace** [comment]
Version 6.1 (6A1052d)

**Comment by GianiVersace** [comment]
for example: i have a login.proto with 3 fields:
required string username = 1;
required string password = 2;
required string pushtoken = 3;

In obj-c i built the login.pb.h and login.pb.m files. I setted the fields on the loginBuilder . I made a login object say LoginBuild = [LoginBuilder build]. I get the data that i have to transfer through [LoginBuild data].
Now, i'm using socket.io to communicate with the server/other devices. If i send a string, or and NSData built from a string, it works fine. But if i send the [LoginBuild data] (which is also and NSData), the server doesn't receive one bit of it.

**Comment by GianiVersace** [comment]
The bytes that the data method returns seem to be fine. I compared them to an android protobuf object that had the same fields. The only difference is that my bytes are in hex, theirs are in dec and i don't see that to be a problem

**Comment by alexeyxo** [comment]
Show me the full code .proto file and obj-с/ swift code. I'm not psychic :)

**Comment by GianiVersace** [comment]
this is the proto : 
message login 
{
  required string username = 1;
  required string password = 2;
  required string pushtoken = 3;
}

This is the obj-c code:

[SIOSocket socketWithHost:@"http://myHost" response:^(SIOSocket *socket)
    {
        _socket = socket;
        
        __weak ViewController *_weakSelf = self;
        
        _socket.onConnect = ^
        {
            NSLog(@"connected");
            
            [_weakSelf testEmit];
            
            
        };
        
        [_socket on:@"testios" callback:^(NSArray *args)
         {
             NSLog(@"on: %@", args);
//             [_weakSelf testEmit];
         }];
        
        _socket.onDisconnect = ^ () {
            NSLog(@"disconnected");
        };
        
        _socket.onError = ^(NSDictionary* error) {
            NSLog(@"%@", error);
        };
    }];

**Comment by GianiVersace** [comment]
this is the testEmit method : 
-(void) testEmit
{
    loginBuilder *loginBuilder = [login builder];

    [loginBuilder setUsername:@"user"];
    [loginBuilder setPassword:@"pass"];
    [loginBuilder setPushtoken:@"push"];
    
    login *LoginBuild = [loginBuilder build];
    
    NSData *data = [LoginBuild data];

      [_socket emit:@"testios" args:@[ data ]];
}

**Comment by alexeyxo** [comment]
Try this:
```objective-c
-(void) testEmit
{
loginBuilder *loginBuilder = [login builder];

[loginBuilder setUsername:@"user"];
[loginBuilder setPassword:@"pass"];
[loginBuilder setPushtoken:@"push"];

login *LoginBuild = [loginBuilder build];

NSData *data = [LoginBuild data];
NSLog(@"%lu",data.length);
[_socket emit:@"testios" args:@[ data ]];
}
```
and get me console logs.

**Comment by GianiVersace** [comment]
here are the logs : 

2015-02-20 14:24:52.136 Test-ProtocolBuffers4[6727:322110] connected
2015-02-20 14:24:52.137 Test-ProtocolBuffers4[6727:322110] 32
2015-02-20 14:24:52.137 Test-ProtocolBuffers4[6727:322110] sent data

**Comment by GianiVersace** [comment]
so i guess the problem isn't coming from your ProtoBuf API, but from the socket API, right?

**Comment by alexeyxo** [comment]
Yes you are right. The problem in socket.

**Comment by GianiVersace** [comment]
Ok. Thanks a lot for your time, alex. Cheers

**Comment by alexeyxo** [comment]
No problem. Thanks.
