### ISSUE TITLE
no member named 'GetEmptyStringAlreadyInited'

### ISSUE THREAD

**Issue by jault3** [alexeyxo/protobuf-swift#4]
Following the directions in the README, I get to step 6, `./build.sh` and it does not successfully complete. A partial stack trace I am getting is included below. If you would like the entire trace let me know, it's rather lengthy and seems like it just repeats the same message anyways. 

Result of `protoc --version` is `libprotoc 2.5.0`. Installed all of those tools listed in the README through homebrew.  Any other info you need let me know.

```
make[2]: *** [swift_primitive_field.o] Error 1
./google/protobuf/descriptor.pb.h:2840:50: error: no member named 'GetEmptyStringAlreadyInited' in namespace 'google::protobuf::internal'
  if (package_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
./google/protobuf/descriptor.pb.h:2848:50: error: no member named 'GetEmptyStringAlreadyInited' in namespace 'google::protobuf::internal'
  if (package_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
./google/protobuf/descriptor.pb.h:2856:50: error: no member named 'GetEmptyStringAlreadyInited' in namespace 'google::protobuf::internal'
  if (package_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
./google/protobuf/descriptor.pb.h:2864:50: error: no member named 'GetEmptyStringAlreadyInited' in namespace 'google::protobuf::internal'
  if (package_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
./google/protobuf/descriptor.pb.h:2872:50: error: no member named 'GetEmptyStringAlreadyInited' in namespace 'google::protobuf::internal'
  if (package_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
./google/protobuf/descriptor.pb.h:2876:75: error: no member named 'GetEmptyStringAlreadyInited' in namespace 'google::protobuf::internal'
    package_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [swift_file.o] Error 1
20 errors generated.
make[2]: *** [swift_extension.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by Freya0Yu** [comment]
I use brew upgrade but the libprotoc is still 2.5 ,what should i do to update my protobuf compiler ?

**Comment by alexeyxo** [comment]
Try this:
```brew install protobuf-swift```

**Comment by Freya0Yu** [comment]
Can it support objective c？

**Comment by alexeyxo** [comment]
Unfortunately, protobuf-swift not support objective-c.

**Comment by Freya0Yu** [comment]
I met those errors when I install protobuf-objc,I'm sorry that I left a note at wrong place .I do as https://github.com/alexeyxo/protobuf-objc told but it does't work.

**Comment by alexeyxo** [comment]
I think, your problem in old version Google Protobuf. Please, remove and install protobuf from homebrew.

**Comment by Freya0Yu** [comment]
Thanks a lot ! Now I have it installed!

**Comment by matejukmar** [comment]
I'm having same issue with https://github.com/alexeyxo/protobuf-objc and I updated/upgraded brew and install latest protobuf.

protoc --version ... returns ... libprotoc 2.6.1

and ./scripts/build.sh   still returns these errors:

./google/protobuf/descriptor.pb.h:3042:50: error: no member named 'GetEmptyStringAlreadyInited' in namespace
      'google::protobuf::internal'
  if (package_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {

Any Ideas what to do to fix?
