### ISSUE TITLE
Support for Swift 1.2

### ISSUE THREAD

**Issue by Riccardo99** [alexeyxo/protobuf-swift#40]
Hi, I want to use `protobuf-swift` in my project on **XCode 6.3 Beta 2**, but I'm getting various errors while doing so. I tried to convert the code, but no success so far.

Can someone make a branch compatible to **Swift 1.2** or something?

Thanks :)

**Comment by alexeyxo** [comment]
I'll add later.

**Comment by dpassage** [comment]
How much later? We're using this in an active project we'd like to get converted over to Swift 1.2. Happy to help with the work, but if it's imminent for you, it may not make sense to duplicated effort.

**Comment by dpassage** [comment]
Thanks!
