### ISSUE TITLE
help needed: error during "How To Install Protobuf" /step 6.: "6.`./scripts/build.sh`"

### ISSUE THREAD

**Issue by petersesztak** [alexeyxo/protobuf-swift#42]
I installed and build the ProtocolBuffers.xcodeproj under Xcode V6.1.1: everything is fine :)

1/ My problem to build protoc compiler:
when I try to build (as `./scripts/build.sh`) I got the following message:
Peter-Sesztaks-MacBook:~ petersesztak$ /Users/petersesztak/protobuf-swift/scripts/build.sh 
+ ./autogen.sh
/Users/petersesztak/protobuf-swift/scripts/build.sh: line 5: ./autogen.sh: No such file or directory

Please, help me how to avoid this.

2/ when I try to use proton compiler a got error message:

Peter-Sesztaks-MacBook:Downloads petersesztak$ protoc Test.proto --swift_out="./"
protoc-gen-swift: program not found or is not executable
--swift_out: protoc-gen-swift: Plugin failed with status code 1.

Any suggestion?
Thanks in advance,
Best Regards,
Péter

**Comment by alexeyxo** [comment]
Try it:
```sh
$ cd /Users/petersesztak/protobuf-swift/
$ ./scripts/build.sh
```

**Comment by petersesztak** [comment]
Big thanks, it worked ! :) (both compiling protoc compiler and using protoc to generate *.proto to *.pb.swift)
thanks again ! -your are lightning FAST ! :)

**Comment by alexeyxo** [comment]
No problem, thanks!
