### ISSUE TITLE
using: project source files of ProtocolBuffers.xcodeproj or should we use as a ProtocolBuffers.framework?

### ISSUE THREAD

**Issue by petersesztak** [alexeyxo/protobuf-swift#43]
Dear Alex,
a short question: we have to use project source files of ProtocolBuffers.xcodeproj (as in current documentation) only or should we use (add it to Xcode) as a framework  (ProtocolBuffers.framework)?
Cheers,
Péter

**Comment by alexeyxo** [comment]
You can use the [Carthage](https://github.com/Carthage/Carthage) for compiling framework. - One time compile and go ahead:)
