### ISSUE TITLE
question: CodedInputStream vs NSInputStream

### ISSUE THREAD

**Issue by petersesztak** [alexeyxo/protobuf-swift#44]
Dear Alexey,
What is the difference between CodedInputStream and NSInputStream?
Another say: what is the intention of CodedInputStream and the methods around it ( *.parseFromCodedInputStream, *.parseFromCodedInputStream)? 

(e.g. we should read / write an instance by a normal NSStream: person.parseFromInputStream(input: NSInputStream) / person.writeToOutputStream(output: NSOutputStream), what is the advantage of using .parseFromCodedInputStream(input: CodedInputStream) ?)

Thanks in advance !
Péter

**Comment by alexeyxo** [comment]
CodedInputStream - this implementation "streams" in the official PB ([Streaming](https://developers.google.com/protocol-buffers/docs/techniques#streaming)). 
CodedInputStream correctly separates message in byte-stream.
I always use CodedInputStream.

**Comment by alexeyxo** [comment]
When you use NSInput/OutputStream, will be used in CodedInput/OutputStream. This is helper methods.

**Comment by petersesztak** [comment]
Perfect !

**Comment by petersesztak** [comment]
The standard way to build up a TPC connection we use:
NSStream.getStreamsToHostWithName(host, port: port, inputStream: &inputStream, outputStream: &outputStream)

Question: how to do that with CodedInputStream and CodedOutputStream streams as NSInputStream and NSOutputStream are privates in your implementation?
(e.g.
private var input:NSInputStream!
private var output:NSOutputStream!
)

Background: normally we use "inputStream!.delegate = ...,  inputStream!.scheduleInRunLoop(.mainRunLoop(), forMode: NSDefaultRunLoopMode) ..., func stream(aStream: NSStream, handleEvent eventCode: NSStreamEvent) {... pattern to handle TCP events (like ErrorOccurred, OpenCompleted, HasBytesAvailable, HasSpaceAvailable, etc).

Do I have to use another approach in case of CodedInputStream, CodedOutputStream?
Best Regards,
Péter

more detailed implementation of our standard TCP streams as follows:

func connect(host: String, port: Int) {
        
        self.host = host
        self.port = port
        
        NSStream.getStreamsToHostWithName(host, port: port, inputStream: &inputStream, outputStream: &outputStream)
        
        if inputStream != nil && outputStream != nil {
            
            // Set delegate
            inputStream!.delegate = self
            outputStream!.delegate = self
            
            // Schedule
            inputStream!.scheduleInRunLoop(.mainRunLoop(), forMode: NSDefaultRunLoopMode)
            outputStream!.scheduleInRunLoop(.mainRunLoop(), forMode: NSDefaultRunLoopMode)
            
            println("Start open()")
            
            // Open!
            inputStream!.open()
            outputStream!.open()
        }
    }


// streams event handling:
func stream(aStream: NSStream, handleEvent eventCode: NSStreamEvent) {
        if aStream === inputStream {
            switch eventCode {
            case NSStreamEvent.ErrorOccurred:
                println("input: ErrorOccurred: \(aStream.streamError?.description)")
                break
            case NSStreamEvent.EndEncountered:
                println("input: EndEncountered")
                break
            case NSStreamEvent.None:
                println("input: None")
                break
            case NSStreamEvent.OpenCompleted:
                println("input: OpenCompleted")
                break
            case NSStreamEvent.HasBytesAvailable:
                println("input: HasBytesAvailable")
                
                 // Here you can `read()` from `inputStream`
                if ( aStream == inputStream){
                var buffer = [UInt8](count: 4096, repeatedValue: 0)
                                while (inputStream!.hasBytesAvailable){
                                    var len = inputStream!.read(&buffer, maxLength: buffer.count)
                                   // ...
                                    }
                                }
                }
                break
           
            case NSStreamEvent.HasSpaceAvailable:
                println("input: HasSpaceAvailable")
                break
            case NSStreamEvent.allZeros:
                println("input: allZeros")
                break
                
            default:
                println("input: default break")
                break
                
            }
        }
        else if aStream === outputStream {
            switch eventCode {
            case NSStreamEvent.ErrorOccurred:
                println("output: ErrorOccurred: \(aStream.streamError?.description)")
                break
            case NSStreamEvent.EndEncountered:
                println("output: OpenCompleted")
                break
            case NSStreamEvent.None:
               println("output: None")
                break
            case NSStreamEvent.OpenCompleted:
                println("output: OpenCompleted")
                break
            case NSStreamEvent.HasBytesAvailable:
                println("output: HasBytesAvailable")
                break
            case NSStreamEvent.HasSpaceAvailable:
                // Here you can write() to `outputStream`
                break
            
            case NSStreamEvent.allZeros:
                println("output: allZeros")
                break
                
            default:
                println("output: default break")
                break
            }
        }
    }
