### ISSUE TITLE
Question: how to integrate CodedInputStream and CodedOutputStream to standard workflow of NSStreams? 

### ISSUE THREAD

**Issue by petersesztak** [alexeyxo/protobuf-swift#45]
The standard way to build up a TPC connection we use:
NSStream.getStreamsToHostWithName(host, port: port, inputStream: &inputStream, outputStream: &outputStream)

Question: how to do that with CodedInputStream and CodedOutputStream streams as NSInputStream and NSOutputStream are privates in your implementation?
(e.g.
private var input:NSInputStream!
private var output:NSOutputStream!
)

Background: normally we use "inputStream!.delegate = ..., inputStream!.scheduleInRunLoop(.mainRunLoop(), forMode: NSDefaultRunLoopMode) ..., func stream(aStream: NSStream, handleEvent eventCode: NSStreamEvent) {... pattern to handle TCP events (like ErrorOccurred, OpenCompleted, HasBytesAvailable, HasSpaceAvailable, etc).

Do I have to use another approach in case of CodedInputStream, CodedOutputStream?
Best Regards,
Péter

more detailed implementation of our standard TCP streams as follows:

func connect(host: String, port: Int) {

    self.host = host
    self.port = port

    NSStream.getStreamsToHostWithName(host, port: port, inputStream: &inputStream, outputStream: &outputStream)

    if inputStream != nil && outputStream != nil {

        // Set delegate
        inputStream!.delegate = self
        outputStream!.delegate = self

        // Schedule
        inputStream!.scheduleInRunLoop(.mainRunLoop(), forMode: NSDefaultRunLoopMode)
        outputStream!.scheduleInRunLoop(.mainRunLoop(), forMode: NSDefaultRunLoopMode)

        println("Start open()")

        // Open!
        inputStream!.open()
        outputStream!.open()
    }
}
// streams event handling:
func stream(aStream: NSStream, handleEvent eventCode: NSStreamEvent) {
if aStream === inputStream {
switch eventCode {
case NSStreamEvent.ErrorOccurred:
println("input: ErrorOccurred: (aStream.streamError?.description)")
break
case NSStreamEvent.EndEncountered:
println("input: EndEncountered")
break
case NSStreamEvent.None:
println("input: None")
break
case NSStreamEvent.OpenCompleted:
println("input: OpenCompleted")
break
case NSStreamEvent.HasBytesAvailable:
println("input: HasBytesAvailable")

             // Here you can `read()` from `inputStream`
            if ( aStream == inputStream){
            var buffer = [UInt8](count: 4096, repeatedValue: 0)
                            while (inputStream!.hasBytesAvailable){
                                var len = inputStream!.read(&buffer, maxLength: buffer.count)
                               // ...
                                }
                            }
            }
            break

        case NSStreamEvent.HasSpaceAvailable:
            println("input: HasSpaceAvailable")
            break
        case NSStreamEvent.allZeros:
            println("input: allZeros")
            break

        default:
            println("input: default break")
            break

        }
    }
    else if aStream === outputStream {
        switch eventCode {
        case NSStreamEvent.ErrorOccurred:
            println("output: ErrorOccurred: \(aStream.streamError?.description)")
            break
        case NSStreamEvent.EndEncountered:
            println("output: OpenCompleted")
            break
        case NSStreamEvent.None:
           println("output: None")
            break
        case NSStreamEvent.OpenCompleted:
            println("output: OpenCompleted")
            break
        case NSStreamEvent.HasBytesAvailable:
            println("output: HasBytesAvailable")
            break
        case NSStreamEvent.HasSpaceAvailable:
            // Here you can write() to `outputStream`
            break

        case NSStreamEvent.allZeros:
            println("output: allZeros")
            break

        default:
            println("output: default break")
            break
        }
    }
}

**Comment by alexeyxo** [comment]
You can use public methods:
```swift
public init (inputStream aInputStream:NSInputStream)
public init(output aOutput:NSOutputStream!, bufferSize:Int32)
public init(output:NSOutputStream)
```
Unfortunately, I can't tell about your problem, because for a long time not worked with NSStream.:(
