### ISSUE TITLE
Nested protobufs aren't working properly

### ISSUE THREAD

**Issue by mhahn** [alexeyxo/protobuf-swift#49]
I have the following directory structure:

```
protobufs
└── services
    ├── organization
    │   ├── actions
    │   │   ├── create_organization.proto
    │   │   └── get_organization.proto
    │   └── containers
    │       ├── organization.proto
    │       └── team.proto
    └── profile
        ├── actions
        │   └── get_extended_profile.proto
        └── containers
            └── profile.proto

7 directories, 6 files
```

The protobufs compile to swift, but the files fail to build. It looks like some of the internal extension lines are misconfigured:

`internal extension Main.Services.Organization{internal struct Containers {.Organization {}}}`
and
`internal extension Main.Services{internal struct Profile {.Actions{internal struct GetExtendedProfile {}}}}`

I can send you a zip of the directory to test with.

**Comment by alexeyxo** [comment]
Hi. Please, send me a zip of the directory. I will look.

**Comment by alexeyxo** [comment]
What command do you use to generate files?

**Comment by mhahn** [comment]
For some reason gmail keeps bouncing the follow up email i'm trying to send.

If you take the zip i sent you and run:
```
mkdir src
tar -xvf protobufs.tar.gz
mv protobufs src
mkdir swift
mkdir swift
find src -type f -name '*.proto' | xargs protoc --proto_path ./src --swift_out swift/
```

that should generate the protobufs with the errors

**Comment by mhahn** [comment]
I'm still having issues with these nested protobufs.

From what I can tell, it seems like the order in which you define the structures you use to represent the package hierarchy matters. I'm not sure how the swift compiler determines the order these will get compiled if the definitions are in different files.

I'm sending you a couple of sample projects that demonstrate the issue.

If all of the definitions are in order within one file, everything builds correctly.

ie something like:```
public struct Services { public struct Organization { public struct Actions { public struct CreateOrganization { }}}}
public extension Services { public struct Profile { public struct Actions { public struct GetExtendedProfile { }}}}
public extension Services.Profile { public struct Containers { public struct Profile { }}}
public extension Services.Organization { public struct Containers { public struct Organization { }}}
public extension Services.Organization.Containers { public struct Team { }}
public extension Services.Organization.Actions { public struct GetOrganization { }}
```
works in a playground.

as opposed to:```
public extension Services.Organization.Actions { public struct GetOrganization { }}
public extension Services.Profile { public struct Containers { public struct Profile { }}}
public struct Services { public struct Organization { public struct Actions { public struct CreateOrganization { }}}}
public extension Services { public struct Profile { public struct Actions { public struct GetExtendedProfile { }}}}
public extension Services.Organization { public struct Containers { public struct Organization { }}}
public extension Services.Organization.Containers { public struct Team { }}
```
which fails with "'Profile' is not a member type of 'Services'"

**Comment by mhahn** [comment]
https://developer.apple.com/swift/blog/?id=7

makes it clear why the above two don't work in the playground, the playgrounds are "order-dependent". i'm not sure why the project i sent you is not "order-independent" as it should be.

**Comment by alexeyxo** [comment]
This is some kind of magic:)

**Comment by alexeyxo** [comment]
I look this example in the weekend.

**Comment by alexeyxo** [comment]
![scrennproto](https://cloud.githubusercontent.com/assets/2980636/7204365/256f67cc-e52a-11e4-96b0-a28a919ec563.png)
This is a bug in Xcode. When I change the order of files - all compiled :)

**Comment by brandonroth** [comment]
@mhahn did you file a bug report on this?  I am having the same problem as you and changing the compile order fixes the problem for me.  I think it would be worth it to add this edge case to the readme so others don't spin their wheels wondering why it doesn't work.

**Comment by mhahn** [comment]
i never did, i guess now we could probably open an issue on the swift code
base?

**Comment by brandonroth** [comment]
I'm planning on creating a sample project to demonstrate the issue and file a bug report.  Thanks for posting your solution of compile order, it saved my day!

**Comment by mhahn** [comment]
thanks to @alexeyxo without his screenshot i wouldn't have known you can adjust compile order ;)
