### ISSUE TITLE
A way of providing compile_for_framework = false for all proto files?

### ISSUE THREAD

**Issue by mattijsf** [alexeyxo/protobuf-swift#50]
Hi 

In our projects we still support iOS 7.0 and therefore can't use embedded dylibs/frameworks. Instead we now added the files from the `runtime-pb-swift` folder to our project. This works fine, but...

We now have to modify our existing .proto files to include the compile_for_framework option:

```proto
import 'google/protobuf/swift-descriptor.proto';
option (.google.protobuf.swift_file_options).compile_for_framework = false;

message XYZ {
...
}
```

Although this works it does mean we can't use our existing `.proto` models out-of-the-box. We use existing `.proto` files that are included via a git submodule reference and shared cross-project / platform. Modifying the `.proto` files in-place is for this particular reason not really a great solution.

Is there any way to instruct `protoc` to generate all the swift files with this flag, thus without adding the import / option statement in each file?

**Comment by alexeyxo** [comment]
Sorry, but no other way.:(
Why you didn't add ```swift-descriptor.proto``` in your repository? - In this case, all platforms can correctly generate ```.proto``` files.

**Comment by mattijsf** [comment]
Thanks. It's not ideal but that is good enough for now. Another options is to fallback to the objective-c variant of protobuf but that has other implications / downsides.
