### ISSUE TITLE
Errors while compiling: does not conform to protocol 'GeneratedMessageProtocol' and is not a member type of 

### ISSUE THREAD

**Issue by turkenh** [alexeyxo/protobuf-swift#52]
I have several protobuf files which are actively used in a project with some other languages, and now need swift versions. I can build .pb.swift files successfully but when I add them to Xcode, I am receiving tons of bugs mainly composed of:
* Type 1 'Foo' does not conform to protocol 'GeneratedMessageProtocol'" 
* 'Foo' is not a member type of 'Bar'

I prepared a minimal example showing this issue:

```
message PStatus {
  optional int64 battery_usage = 1;
  optional int64 max_battery_usage = 2;
  message PCardVoltageStatus
  { 
    message PCard
    {
      optional string card_name = 1;
      optional string no = 2;
    };
    repeated PCard card = 1;
  };
};
```
If you build .pb.swift file from this example and add to xcode, you should also get those errors.

**Comment by alexeyxo** [comment]
1. Have you added runtime library into the project?
2. You should update your protobuf-swift compiler and runtime library from repository.
Your example works for me.

**Comment by turkenh** [comment]
I have followed all steps in "How To Install Protobuf" section under readme
1. Do you mean adding ./src/ProtocolBuffers/ProtocolBuffers.xcodeproj in my project? I also added generated .framework file to my project accordingly. 
2. How can I make those updates? Are these something different which is not mentioned in readme? 

I cloned latest repo and build and followed all steps in how to install section. But still having problems? I think I am missing something...

**Comment by alexeyxo** [comment]
For some reason, your project does not see ProtocolBuffers.framework. But I can't reproduce this.

**Comment by turkenh** [comment]
But it is very strange because I can compile following with no problem:
```
message SearchResponse {
    message Result {
      optional string card_name = 1;
      required string no = 2;
    };
    repeated Result result = 1;
};
```

But receive those errors with a count of 55, with the following:
```
message SearchResponse {
    message PResult {
      optional string card_name = 1;
      required string no = 2;
    };
    repeated PResult result = 1;
};
```
Just changed Result-->PResult, since my messages have that prefix.

**Comment by alexeyxo** [comment]
ooohhh... this is bug...:) 
I can fix it by this evening.

**Comment by turkenh** [comment]
Happy to hear not being alone with this:)
Thanks a lot...

**Comment by alexeyxo** [comment]
Try this

**Comment by turkenh** [comment]
Yes, thats working.
Thank you very much...
