### ISSUE TITLE
About update xcode6.3,Pods-ProtocolBuffers-Swift have many error

### ISSUE THREAD

**Issue by zhouzizi** [alexeyxo/protobuf-swift#53]
/Pods/ProtocolBuffers-Swift/src/ProtocolBuffers/runtime-pb-swift/GeneratedMessage.swift:22:11: Class methods are only allowed within classes; use 'static' to declare a static method

**Comment by zhouzizi** [comment]
(null): "__TWPVSs5Int64Ss25IntegerLiteralConvertible", referenced from:

**Comment by zhouzizi** [comment]
//Pods/ProtocolBuffers-Swift/src/ProtocolBuffers/runtime-pb-swift/GoogleProtobuf_Descriptor.pb.swift:669:65: 'MessageBuilder' is not convertible to 'Google.Protobuf.FileDescriptorProtoBuilder'; did you mean to use 'as!' to force downcast?

**Comment by mattijsf** [comment]
You can use the https://github.com/alexeyxo/protobuf-swift/tree/swift1.2 branch until the fixed are merged

**Comment by zhouzizi** [comment]
how to use from cocoapods

**Comment by zhouzizi** [comment]
But when i Compile ".proto" files, the ".pb.swift" files hava not update swift 1.2

**Comment by alexeyxo** [comment]
You should update protobuf-swift compiler and cocoapods.
