### ISSUE TITLE
cant compile swift_out

### ISSUE THREAD

**Issue by kevinhury** [alexeyxo/protobuf-swift#55]
protoc-gen-swift: program not found or is not executable
--swift_out: protoc-gen-swift: Plugin failed with status code 1.

**Comment by alexeyxo** [comment]
How do you install the compiler? Please, send me installation logs.

**Comment by kevinhury** [comment]
I installed protobuf using brew and -swift through carthage.
I guess I did something wrong?

When I try to compile cpp files using
protoc shape.proto --cpp_out="./"
there are no problems, but when I change the output directive to --swift_out I get the error in the first comment.

Thanks for the quick comment btw

**Comment by alexeyxo** [comment]
Try this:
https://github.com/alexeyxo/protobuf-swift#how-to-install-protobuf

**Comment by kevinhury** [comment]
Thanks. I had problems cloning the repository but I just downloaded the zip.
running the ./scripts/build.sh fixed the problem.
