### ISSUE TITLE
brew formula

### ISSUE THREAD

**Issue by falsecz** [alexeyxo/protobuf-swift#56]
Hi, I've prepared brew formula for automatic installation

```
brew tap falsecz/misc
brew install falsecz/misc/swift-protobuf
```

https://github.com/falsecz/homebrew-misc/blob/master/Formula/swift-protobuf.rb

**Comment by alexeyxo** [comment]
Thanks. I created a pull request in the official homebrew repository.
https://github.com/Homebrew/homebrew/pull/39101

**Comment by alexeyxo** [comment]
Done. Close.
