### ISSUE TITLE
Parsing uses NSException.raise to communicate errors, which can't be handled in pure Swift

### ISSUE THREAD

**Issue by vgatto** [alexeyxo/protobuf-swift#59]
From my Googling, I can't find a pure Swift way of handling NSException. I'm new to both Swift and Objective-C, so this might just be my ignorance.  If there's a way to handle this in Swift, I'd be grateful if you pointed it out.

Otherwise, parsing errors are definitely recoverable (e.g. retry a corrupted RPC), so attempting to expose them via NSError in a callback or builder attribute would be helpful.

**Comment by vgatto** [comment]
Just realized this is a duplicate, closing.

**Comment by basysteixeira** [comment]
Hello vgatto,
I have the same issue, but I don't found the "original" issue that you mentioned. What is the issue number? How do you solve this problem?
Thank you in advance.
Joao
