### ISSUE TITLE
Naming inconsistency breaks compile when using prefix option with message-level enums

### ISSUE THREAD

**Issue by vgatto** [alexeyxo/protobuf-swift#60]
It looks like the fix to https://github.com/alexeyxo/protobuf-swift/issues/57 introduced a bug.
Now, message level (nested) enums have a naming inconsistency in the generated code.

```
import "google/protobuf/swift-descriptor.proto";
option (.google.protobuf.swift_file_options).class_prefix = "PB";

message IceCreamCone {
  optional int32 scoops = 1;
  enum Flavor {
    CHOCOLATE = 1;
    VANILLA = 2;
  }
  optional Flavor flavor = 2;
}
```

The generated enum is correctly named `PBFlavor` and is declared within `PBIceCreamCone` but the `flavor` variable is given the type `PBIceCreamCone.Flavor`.

**Comment by alexeyxo** [comment]
Sorry...:((
