### ISSUE TITLE
Equality is implemented but != doesn't work as expected

### ISSUE THREAD

**Issue by mattijsf** [alexeyxo/protobuf-swift#61]
```proto
message ProtoPoint {
    required float latitude = 1;
    required float longitude = 2;
}
```

This works, notice that the `XCTAssert` takes an explicit inverse of the result of == :
```swift
func testProtoPointWorks() {
    var point1 = ProtoPoint.builder().setLatitude(1.0).setLongitude(1.0).build()
    var point2 = ProtoPoint.builder().setLatitude(2.0).setLongitude(2.0).build()
    
    XCTAssert(point1.latitude == 1.0, "")
    XCTAssert(point2.latitude == 2.0, "")
    
    // Succeeds, calls the == function from ProtoPoint.pb.swift as expected
    XCTAssert(!(point1 == point2), "")
}
```
This doesn't work, only last `XCTAssert` is modified into != without the explicit inverse:
```swift
func testProtoPointShouldWork() {
    var point1 = ProtoPoint.builder().setLatitude(1.0).setLongitude(1.0).build()
    var point2 = ProtoPoint.builder().setLatitude(2.0).setLongitude(2.0).build()
    
    XCTAssert(point1.latitude == 1.0, "")
    XCTAssert(point2.latitude == 2.0, "")
    
    // Fails, should call the == function from ProtoPoint.pb.swift and take the inverse just like the testRegularPoint() does. But that doesn't happen.
    XCTAssert(point1 != point2, "")
}
```

I believe it should follow the same logic as "regular" class like in the example below:

```swift
class RegularPoint: Equatable {
    var latitude:Float = Float(0)
    var longitude:Float = Float(0)
}


func == (lhs: RegularPoint, rhs: RegularPoint) -> Bool {
    return lhs.latitude == rhs.latitude &&
        lhs.longitude == rhs.longitude
}

class RegularPointEqualityTest: XCTestCase {
    func testRegularPoint() {
        var point1 = RegularPoint()
        point1.latitude = 1.0
        point1.longitude = 1.0
        
        var point2 = RegularPoint()
        point2.latitude = 2.0
        point2.longitude = 2.0
        
        // works fine, calls the == function and takes the inverse implicitly (put break point to check)
        XCTAssert(point1 != point2, "")
    }
}
```

When putting a breakpoint on the `==` function within the genered protobuf `ProtoPoint` swift file I notice that the == function is being called when comparing using == but not when comparing using != which is strange imo since swift does call the `==` function when comparing `RegularPoint` using `!=`

I created a sample project here: https://github.com/mattijsf/ProtobufEqualityTest

**Comment by mattijsf** [comment]
Do you have any idea why it is necessary to implement != operator explicitly (https://github.com/alexeyxo/protobuf-swift/issues/61)? Why isn't swift just calling the inverse of == like it does with my `RegularPoint`

**Comment by alexeyxo** [comment]
I have no ideas, why so occurs.%(

**Comment by alexeyxo** [comment]
I understood!!! Take a look last commit. If you have any question, write me.

**Comment by mattijsf** [comment]
Ah! The concrete message class should have been `Equatable` not the abstract message class. Right?

If that is the case I still find it a bit confusing that it does call the `==` operator of `ProtoPoint` because it is implemented / overridden explicitly in the subclass. But apperently Swift prefers the take the inverse of the `==` operator within it's superclass `AbstractMessage` when using `!=` because that is designated class that conforms to `Equatable`. I have mixed feelings about that... but yeah...
