### ISSUE TITLE
No such module 'ProtocolBuffers' in unitests when I use it with Cocoapods

### ISSUE THREAD

**Issue by jamesweb1** [alexeyxo/protobuf-swift#62]
I'm very new to iOS development. This is strange errors for me, and I try hundred of times to find out the errors.
I'd like to use protobuf-swift in my cocoapods project so that I generate the Podfile as follows:
```
use_frameworks!
pod 'ProtocolBuffers-Swift', '~> 1.6'
```
I have a brand new Xcode cocoa touch framework project. Then, I generate my Xcode workspace by "pod install". I try to build my project and it build successfully before I add protobuffer's swift file. After I add my "Person.pb.swift" to my project with both target (framework and test). It shows build fail cause
from "No such module 'ProtocolBuffers'" in my "Person.pb.swift".

Finally, I find if I remove file "Person.pb.swift" from Compile Sources of test target and It will build successfully. So I guess the Xcode cannot find my 'ProtocolBuffers' module under unittest, but it can perform well under framework(normal code). How to solve this issue?

![error](https://cloud.githubusercontent.com/assets/6868915/7448523/b8990c3e-f24e-11e4-96b0-d183281f69e5.jpg)

ps. if i remove Person.pb.swift of Compile Sources, my project will build successfully.

**Comment by alexeyxo** [comment]
Hi! 
Try this Podfile:
```
use_frameworks!
link_with 'bditester', 'bditesterTests'
pod 'ProtocolBuffers-Swift'
```

**Comment by jamesweb1** [comment]
Surprisingly! This solved my problem. Should I read something to understand more about cocoapods. I always try to change something(ex. targets, linked frameworks and libraries, compile sources). But it makes no effect for me. Therefore I need to always use "link_with 'bditester', 'bditesterTests'" for all my Podfile? I really didn't see this instruction in the cocoapods page.

**Comment by alexeyxo** [comment]
You should use link_with option for all deployment targets in your project. 
https://guides.cocoapods.org/syntax/podfile.html#link_with
