### ISSUE TITLE
Crash when nested object not populated

### ISSUE THREAD

**Issue by mhahn** [alexeyxo/protobuf-swift#63]
Lets say I have something like the following:

proto file:
```
message Child {
    optional bool isWellBehaved = 1;
    optional string name = 2;
}
message Parent {
    optional Child child = 1; 
}
```

swift:
```
let parent = Parent.parseFromNSData(data)
if parent.child.isWellBehaved {

}
```

the above will cause a crash if the parent does not have a child since "child" is set to nil.

likewise if i did:
```
var builder = Parent.builder()
builder.child = Child.builder().setIsWellBehaved(true).setName("child").build()
var parent = builder.build()
println(parent.child.isWellBehaved)
builder.clearChild()
parent = builder.build()
println(parent.child.isWellBehaved)
```

would crash on the 2nd printing of "isWellBehaved" since "clearChild" sets `child = nil`.

this logic goes against what the compiler is telling me to expect and seems to differ from other implementations. if the child isn't present "hasChild" should be false, but it should be an empty child object.

**Comment by alexeyxo** [comment]
In my opinion, you don't correctly using implicitly unwrapped optional properties.
This example worked fine:
```swift
var builder = Parent.builder()
builder.child = Child.builder().setIsWellBehaved(true).setName("child").build()
var parent = builder.build()
println(parent.child.isWellBehaved)
builder.clearChild()
parent = builder.build()
println(parent.child?.isWellBehaved)
```

**Comment by mhahn** [comment]
ok, I buy that.
