### ISSUE TITLE
Add option for generating mutable classes.

### ISSUE THREAD

**Issue by vgatto** [alexeyxo/protobuf-swift#64]
It would be nice if the generated classes were mutable. The current API makes using the generated classes for storing runtime state quite burdensome. The builder works fine for simple messages but really breaks down for sub-messages.

Example:
```
message User {
  optional int64 user_id = 1;
  optional string name = 2;
}

message Post {
  optional int64 post_id = 1;
  optional string title = 2;
  optional User user = 3;
}
```

If I have a Post builder, changing the title is easy:

```
let builder = Post.builder();
builder.title = "New Title";
```

Changing the user's name is more involved, because the builder does not consist of builders for sub-messages, but built immutable message. For example, the following doesn't work:

```
let builder = Post.builder();
builder.user.name = "new name";
```

Instead the following needs to be done:

```
let builder = Post.builder();
builder.setUser(
  builder.user.toBuilder()
  .setName("new name")
  .build());
```

Hopefully it would be straight forward to add a Swift compiler option to remove the private (set) from variables, though some extra management for hasField would probably be necessary.

**Comment by alexeyxo** [comment]
It's not easy... 
And this big violation of pattern```(Builder)```. The ```Protobuf-Swift``` works like a original ```Protobuf(Java)```, so, I don't think, that it is worth changing habitual decisions.

**Comment by vgatto** [comment]
Would you consider adding an API similar to Java's sub-builders? This would alleviate a lot of the pain around mutating messages.

**Comment by alexeyxo** [comment]
Give me example, please.
I don't see the problem in use of already implemented and usual solutions.

**Comment by vgatto** [comment]
This is taken directly from the Protobuf Java documentation (https://developers.google.com/protocol-buffers/docs/reference/java-generated#sub-builders):

If you have a Baz message already, and want to change the deeply nested val in Foo. Instead of:
```
  baz = baz.toBuilder().setBar(
      baz.getBar().toBuilder().setFoo(
          baz.getBar().getFoo().toBuilder().setVal(10).build()
      ).build()).build();
```
You can write:

```
  Baz.Builder builder = baz.toBuilder();
  builder.getBarBuilder().getFooBuilder().setVal(10);
  baz = builder.build();
```

**Comment by alexeyxo** [comment]
Ok. I'll add them.
