### ISSUE TITLE
Add an option to expose generated swift classes to Obj-C

### ISSUE THREAD

**Issue by victorcotap** [alexeyxo/protobuf-swift#65]
Right now, generated classes do not sport the @objc tag or inherit from NSObject which makes them invisible to Objective-C
Also using struct for name-spacing definitively hides them from Objective-C as well

Could it be possible to add an option to generate classes with @objc classes and no namespace ?

**Comment by alexeyxo** [comment]
It is impossible, there are many reasons...
For example, nested messages in protobuf use swift nested class... Objc has no nested messages. And e.t.c 
Therefore - Protobuf-objc for objective-c projects, Protobuf-Swift for Swift projects.

**Comment by victorcotap** [comment]
Thanks for the insight and thanks for the great tool!
