### ISSUE TITLE
Play Framework

### ISSUE THREAD

**Issue by byroncoetsee** [alexeyxo/protobuf-swift#66]
Hi there,

I'm trying to communicate from Swift to a server running the play framework.

I've tried the "option (.google.protobuf.swift_file_options).compile_for_framework = false;" thing but that just removes the "import ProtocolBuffers" line which then breaks everything.

Do you know of a way or am I doing something wrong?

Thanks for this rather life saving bunch of code though :)

**Comment by alexeyxo** [comment]
Have you added  "runtime-pb-swift" directory in the project?

**Comment by byroncoetsee** [comment]
In the xcode project? Adding it makes no difference as nothing is referencing it... 

I've tried adding "runtime-pb-swift" manually by dragging it in and adding it to the "protocolBuffers-Swift" target that CocoaPods added.

PS. I originally installed everything via CocoaPods

**Comment by byroncoetsee** [comment]
Let me just add, I might be misunderstanding what you mean by "framework". I'm trying to communicate with the Play Framework, not generating something for a framework...

**Comment by alexeyxo** [comment]
If you installed from cocoapods, why you use ```compile_for_framework``` option? This is not right...
