### ISSUE TITLE
InvalidProtocolBuffer

### ISSUE THREAD

**Issue by zhouzizi** [alexeyxo/protobuf-swift#72]
---------
 Terminating app due to uncaught exception 'InvalidProtocolBuffer', reason: 'Invalid Tag: last tag 100'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010452fc65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000103db0bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010452f8a9 -[NSException raise] + 9
	3   ProtocolBuffers                     0x0000000102d55d1a _TFC15ProtocolBuffers16CodedInputStream15checkLastTagWasfS0_FVSs5Int32T_ + 954
	4   ProtocolBuffers                     0x0000000102d4dd39 _TFC15ProtocolBuffers22AbstractMessageBuilder13mergeFromDatafDS0_FTCSo6NSData17extensionRegistryCS_17ExtensionRegistry_DS0_ + 185
--------
I cannot find out witch parameter has error,how can i find out it?

**Comment by alexeyxo** [comment]
I think your problem in bad proto-data from server. You have got not full packet of data.

**Comment by zhouzizi** [comment]
But the server push the same data to android client，it doesnot has problem.I donot know does the data missing parameter

**Comment by alexeyxo** [comment]
I need more details about the problem. How can I reproduce?

**Comment by zhouzizi** [comment]
I can not  reproduce too,it happens sometimes.The data was got from server ,im msg.So ...

**Comment by alexeyxo** [comment]
I think the problem may be in the data type. Could you show me ```.proto``` file?

**Comment by zhouzizi** [comment]
The mail has been sent.

**Comment by alexeyxo** [comment]
You should say me what type of field threw this exception and what values sent from server.

**Comment by zhouzizi** [comment]
//发送公聊
message ResMsgSendGChatInfoV100{
	required uint64 sgmsgid = 1;//服务端消息id
	required uint64 uid = 2;//消息发送人
	required uint64 guildid = 3;//消息公会id
	required string content = 4;//消息内容体
	required uint64 inputtime = 5;//消息发送时间
}
OR
message ResMsgSendChatInfoV100{
	required uint64 smsgid = 1;//服务端消息id
	required uint64 uid = 2;//消息发送人
	required uint64 touid = 3;//消息接受人
	required string content = 4;//消息内容体
	required uint64 inputtime = 5;//消息发送时间
}
