### ISSUE TITLE
Proto 3 Compiler

### ISSUE THREAD

**Issue by vyshane** [alexeyxo/protobuf-swift#73]
How can I test out the Proto 3 Swift compiler?

Here's what I've tried:
```bash
$ brew install protobuf --devel
...
$ protoc --version
libprotoc 3.0.0
$ cd protobuf-swift
$ ./scripts/build.sh
```

I'm getting a bunch of errors like the following:
```
In file included from swift_file.cc:23:
./google/protobuf/descriptor.pb.h:17:2: error: This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
```

Any chance we could have version 2.0 of protobuf-swift via Homebrew?

**Comment by alexeyxo** [comment]
You should use ```Compiler2.0-ProtoBuf3.0-Swift2.0``` or ```Compiler2.0-ProtoBuf3.0-Swift1.2 ``` branches. I do not added new brew formula.

**Comment by alexeyxo** [comment]
I don't know how to write formula with installation ```depends_on "protobuf"``` ```--devel``` flag.

**Comment by vyshane** [comment]
Thanks @alexeyxo, I managed to get my .proto files compiled using `Compiler2.0-ProtoBuf3.0-Swift2.0`.

Alas, I'm not familiar Homebrew formulas and I can't help much here. From the half hour of research that I've just done, it seems that we indeed can't have a `depends_on` with a `--devel` flag.

**Comment by alexeyxo** [comment]
Thanks. Close.
