### ISSUE TITLE
Import protobuf-swift using Cocoapods

### ISSUE THREAD

**Issue by skyylex** [alexeyxo/protobuf-swift#74]
I have some problems with an importing protobuf-swift using Cocoapods. In instructions section was mentioned about usage of "use_framework" option, but dash ("-") in the name of the Framework isn't allowed for the name of a framework for import instruction. There is an option related to replacing dash with underscore symbol, but this scenario also doesn't work.

**Comment by alexeyxo** [comment]
Let me see your podfile, please.

**Comment by skyylex** [comment]
platform :osx, '10.10'

     use_frameworks!
     pod 'ProtocolBuffers-Swift'

**Comment by alexeyxo** [comment]
```swift
//
//  ViewController.swift
//  Podtest
//
//  Created by Alexey Khokhlov on 14.07.15.
//  Copyright (c) 2015 Alexey Khokhlov. All rights reserved.
//

import Cocoa
import ProtocolBuffers
class ViewController: NSViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
    }

    override var representedObject: AnyObject? {
        didSet {
        // Update the view, if already loaded.
        }
    }
}
```

My test-project was working fine with cocoapods.

**Comment by skyylex** [comment]
Thanks for help. I used ProtocolBuffers-Swift as a name of the framework to import.
