### ISSUE TITLE
how to update  branch swift-2.0 use cocoapods?

### ISSUE THREAD

**Issue by zhouzizi** [alexeyxo/protobuf-swift#76]
i have use Compiler2.0-ProtoBuf3.0-Swift2.0 to update pod ,but the xx.pb.swift don't support swift 2.0

**Comment by zhouzizi** [comment]
how install the compiler to support swift 2.0.。

**Comment by alexeyxo** [comment]
You should clone branches ```Compiler2.0-ProtoBuf2.6-Swift2.0``` or ```Compiler2.0-ProtoBuf3.0-Swift2.0``` . After that run ```./scripts/build.sh```.

**Comment by alexeyxo** [comment]
Generated files use names  ```xx.proto.swift```

**Comment by zhouzizi** [comment]
Generated   xx.pb.swift ,its right?

**Comment by alexeyxo** [comment]
No. The new compiler generates files consisting of names ```xx.proto.swift```.
For example:
```user.proto --> User.proto.swift```

**Comment by zhouzizi** [comment]
run ./scripts/build.sh->

6 errors generated.
make[2]: *** [swift_oneof.o] Error 1
make[2]: *** Waiting for unfinished jobs....
4 errors generated.
make[2]: *** [swift_generator.o] Error 1
4 errors generated.
make[2]: *** [swift_enum.o] Error 1
mv -f .deps/main.Tpo .deps/main.Po
4 errors generated.
make[2]: *** [swift_enum_field.o] Error 1
4 errors generated.
make[2]: *** [swift_message_field.o] Error 1
4 errors generated.
4 errors generated.
make[2]: *** [swift_map_field.o] Error 1
make[2]: *** [swift_file.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by alexeyxo** [comment]
I think you need install Protobuf 3.0.
Run:
```protoc --version```

**Comment by zhouzizi** [comment]
How to install Protobuf 3.0
I have run ->
:git clone -b Compiler2.0-ProtoBuf3.0-Swift2.0 https://github.com/alexeyxo/protobuf-swift.git
:./scripts/build.sh.
but the  version still is libprotoc 2.5.0

**Comment by alexeyxo** [comment]
```libprotobuf``` - is established with ```protoc```.
```protoc``` - this is original protobuf compiler. He is supporting languages ```java/c++/python```. For other languages you should install plugins, ```protobuf-swift``` - is a plugin.
You should install new version of Protocol Buffers.
From homebrew:
```brew update && brew upgrade && brew install protobuf``` - protobuf 2.6
For this one you should use branch ```Compiler2.0-ProtoBuf2.6-Swift2.0```
If you want use ```Protobuf 3.0```, you should run ```brew install protobuf --devel``` and use ```Compiler2.0-ProtoBuf3.0-Swift2.0```.

**Comment by zhouzizi** [comment]
$ brew install protobuf --devel
==> Downloading https://github.com/google/protobuf/archive/v3.0.0-alpha-3.1.tar.
Already downloaded: /Library/Caches/Homebrew/protobuf-3.0.0-alpha-3.1.tar.gz
==> ./autogen.sh

Google Test not present.  Fetching gtest-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:16 --:--:--     0curl: (7) Failed to connect to googletest.googlecode.com port 443: Operation timed out

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
protobuf-c needs c++11 option https://github.com/Homebrew/homebrew/issues/30320

**Comment by zhouzizi** [comment]
1.$  brew install protobuf
2.$ protoc --version
the version is libprotoc 2.6.1
3.$ brew uninstall protobuf
-》Uninstalling /usr/local/Cellar/protobuf/2.6.1... (118 files, 7.2M)
4.brew install protobuf --devel
then show:
==> Downloading https://github.com/google/protobuf/archive/v3.0.0-alpha-3.1.tar.
Already downloaded: /Library/Caches/Homebrew/protobuf-3.0.0-alpha-3.1.tar.gz
==> ./autogen.sh

Google Test not present. Fetching gtest-1.7.0 from the web...
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- 0:01:16 --:--:-- 0curl: (7) Failed to connect to googletest.googlecode.com port 443: Operation timed out

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
protobuf-c needs c++11 option Homebrew/homebrew#30320

**Comment by alexeyxo** [comment]
I don't know why you can't install protobuf 3.0. I can't reproduce this problem.

**Comment by zhouzizi** [comment]
I have install libprotoc 3.0，but I want back to  libprotoc 2.6.1 .So I  run 'brew uninstall protobuf' and run 'brew install protobuf' ,and the 'protoc --version' is libprotoc 2.6.1  ,but compile the xx.proto and new file named xxx.proto.swift ,not named xxx.pd.swift...How real back to  protoc 2.6

**Comment by zhouzizi** [comment]
I have install libprotoc 3.0，but I want back to  libprotoc 2.6.1 .So I  run 'brew uninstall protobuf' and run 'brew install protobuf' ,and the 'protoc --version' is libprotoc 2.6.1  ,but compile the xx.proto and new file named xxx.proto.swift ,not named xxx.pd.swift...How real back to  protoc 2.6

**Comment by zhouzizi** [comment]
How to back protoc 3.0 back to protoc 2.0....

**Comment by nirry** [comment]
@alexeyxo  i now also in the upgrade problem,my protoc version 2.6.1, can't up to 3.0.0....

**Comment by alexeyxo** [comment]
@nirry 
```brew install protobuf --devel```

**Comment by nirry** [comment]
==> Downloading https://github.com/google/protobuf/archive/v3.0.0-alpha-3.1.tar.
Already downloaded: /Library/Caches/Homebrew/protobuf-3.0.0-alpha-3.1.tar.gz
==> ./autogen.sh
Last 15 lines from /Users/ningzi/Library/Logs/Homebrew/protobuf/01.autogen.sh:
2015-10-22 20:05:06 +0800

./autogen.sh

Google Test not present.  Fetching gtest-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0curl: (7) Failed to connect to googletest.googlecode.com port 443: Operation timed out

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Error: Operation already in progress for protobuf https://github.com/Homebrew/homebrew/issues/43520
protobuf-c needs c++11 option https://github.com/Homebrew/homebrew/issues/30320


@alexeyxo

**Comment by alexeyxo** [comment]
@nirry 
You should ask questions in official google repo.

**Comment by nirry** [comment]
@alexeyxo  Think you
