### ISSUE TITLE
Can't build with deployment target 8.0

### ISSUE THREAD

**Issue by zhouzizi** [alexeyxo/protobuf-swift#77]
Module file's minimum deployment target is ios8.4 v8.4: /Users/myFile/Library/Developer/Xcode/DerivedData/Quji-ekkeyklemuxvqzbivbxsvkpmzlqa/Build/Products/Debug-iphonesimulator/ProtocolBuffers.framework/Modules/ProtocolBuffers.swiftmodule/x86_64.swiftmodule

**Comment by alexeyxo** [comment]
I think, that means, your current project has need "Deployment Target" >= iOS 8.0.

[Apple](https://forums.developer.apple.com/thread/5018)
[Solution 1](http://stackoverflow.com/questions/29307117/error-module-files-minimum-deployment-target-is-ios8-3-v8-3)
[Solution 2](http://stackoverflow.com/questions/29750628/sqlite-swift-build-error-module-files-minimum-deployment-target-is-ios8-3-v8-3)
