### ISSUE TITLE
Support for delimited encoded object

### ISSUE THREAD

**Issue by abagmut** [alexeyxo/protobuf-swift#78]
Can you please add support for delimited object encoding/decoding

**Comment by alexeyxo** [comment]
Give me please documentation link for this improvement.

**Comment by abagmut** [comment]
https://developers.google.com/protocol-buffers/docs/encoding?hl=en
here is example implemented on Objective-C https://github.com/mingchen/protobuf-ios

**Comment by DouglasHeriot** [comment]
I’ve not heard of delimited encoding before – after some Googling, it looks like it’s a feature that’s part of the official Java API, but hasn’t made it into anything else?

It’s exactly what I was about to implement myself for sending protobufs down a TCP socket.
Basically just put a uint32 at the start of each message so you know how much to read.

Here’s an actual C++ implementation by Kenton (the original author of the Java one too) of reading and writing from delimited streams:
http://stackoverflow.com/a/22927149/466698

I may have a go at adding this sometime soon as I’m about to need it, and it looks pretty simple.

**Comment by alexeyxo** [comment]
I will add on the weekend.

**Comment by abagmut** [comment]
I will be very grateful if you can do so.
But it isn't so simple as @DouglasHeriot describes, because if message length is longer the 127 bytes it mark first bit of lenght byte and add one another length byte
So it is necessary to keep this in mind for encoding as well

**Comment by alexeyxo** [comment]
You can testing this improvement, but I have no time for writing Unit Tests. I have planning finish writing Unit Tests in Sunday.

**Comment by alexeyxo** [comment]
Done. On the weekend I will update Podspec and Homebrew.

**Comment by alexeyxo** [comment]
Done.
