### ISSUE TITLE
protobuf v3.0.0-alpha-3.1

### ISSUE THREAD

**Issue by bikbah** [alexeyxo/protobuf-swift#79]
I have protobuf v3.0.0-alpha-3.1 installed and when I run **./scripts/build.sh** I get errors like:
1) This file was generated by an older version of protoc which is
2) incompatible with your Protocol Buffer headers. Please
3) regenerate this file with a newer version of protoc

How can I use protobuf "syntax 3"?

**Comment by alexeyxo** [comment]
You should clone branches ```Compiler2.0-ProtoBuf3.0-Swift2.0``` or  ```Compiler2.0-ProtoBuf3.0-Swift1.2```. After that, run ./scripts/build.sh.

**Comment by bikbah** [comment]
thanx
