### ISSUE TITLE
Compilation time is horrible

### ISSUE THREAD

**Issue by mhahn** [alexeyxo/protobuf-swift#81]
This is more of an issue with swift not caching correctly, but its starting to take up to 15-30 minutes to compile our protobuf files when we make changes. We have 104 protobuf files right now. 

I'm curious if you've run into anything similar or have any work arounds for it. I'm not sure if swift 2.0 is going to help alleviate the issues.

**Comment by alexeyxo** [comment]
This problem has a Xcode(LLVM) and are not problems in a protobuf-swift. Apple Radar has a much information on this theme.

**Comment by mhahn** [comment]
Yea, I wasn't sure if it might be worth doing something similar to wire where you trim down the lines of code, but thats not solving the problem with xcode.

Thanks!
