### ISSUE TITLE
Cannot import module being compiled

### ISSUE THREAD

**Issue by monzy613** [alexeyxo/protobuf-swift#82]
hello i'm using swift 2.0 in Xcode 7.0 and use cocoapod to make a xcodeworkspace. and when i build it failed and show this error
![snip20150830_1](https://cloud.githubusercontent.com/assets/12622268/9566010/0b6e357e-4f24-11e5-8443-8673f6f89e32.png)

the pod file is
use_frameworks!
link_with 'tester'
pod 'ProtocolBuffers-Swift'

**Comment by alexeyxo** [comment]
Currently, versions in cocoapods have not supporting Xcode7. You need use branches marked as `Swift2.0`.
