### ISSUE TITLE
Problem with Swift 2

### ISSUE THREAD

**Issue by kiokumicu** [alexeyxo/protobuf-swift#87]
Hi!
Install with pod instruction 
pod 'ProtocolBuffers-Swift', :git => 'https://github.com/alexeyxo/protobuf-swift.git', :branch => 'ProtoBuf3.0-Swift2.0'

Generate proto.swift file from .proto file

When build project got a many errors like this:
Call can throw, but it is not marked with 'try' and the error is not handled
Redundant conformance of 'Method' to protocol 'Hashable'

All this errors from my proto.swift file

What I'm doing wrong?

**Comment by alexeyxo** [comment]
You should manually update your compiler.

**Comment by kiokumicu** [comment]
Can I do it with Homebrew ?

**Comment by alexeyxo** [comment]
Homebrew supports only the stable version - Protobuf 2.6. You can update manually, without homebrew.

**Comment by kiokumicu** [comment]
Well, it's probably my fault.
I do not need the ProtoBuf3.0. The problem appeared after I update XCode to 7.

**Comment by alexeyxo** [comment]
Ok. Protobuf-swift from cocoapods and the compiler from Homebrew are supporting XCode 7.

**Comment by kiokumicu** [comment]
This is what I have after update to XCode 7
![Image of Erors](http://dl2.joxi.net/drive/0011/1461/751029/150917/f0ae274642.jpg)

**Comment by alexeyxo** [comment]
You should update compiler and pod library after that regenerate all .proto files.

**Comment by kiokumicu** [comment]
Using ProtocolBuffers-Swift (2.2)
```
protoc --version
libprotoc 2.6.1
```
And I already regenerate .proto file

**Comment by alexeyxo** [comment]
Try this:
```
brew update && brew upgrade && brew install protobuf-swift
```

**Comment by kiokumicu** [comment]
Thanks!
Most of errors disappear, but couples stay
![Image of Error](http://dl2.joxi.net/drive/0011/1461/751029/150917/bdaef800df.jpg)

**Comment by alexeyxo** [comment]
You sholud use error-handling.

**Comment by kiokumicu** [comment]
I can use error-handling only in Swift 2 and iOS 9, but I need support iOS 8. Or am I wrong?

**Comment by alexeyxo** [comment]
Error handling is not related to a particular platform.

**Comment by kiokumicu** [comment]
Thanks a lot!

**Comment by nirry** [comment]
@alexeyxo 

I also encountered the same problem after upgrade Xcode, execute the command "brew update && brew upgrade && brew install protobuf-swift" without any response,after where I wrong?

**Comment by alexeyxo** [comment]
@nirry you should update runtime-library from cocoapods or etc

**Comment by nirry** [comment]
@alexeyxo  how i do it ?  can you give me some references ?

**Comment by kranjanford** [comment]
hi alexeyxo ,
how could i use protobuf Protobuf2.6-Swift3.0 using cocoa pod.
pod 'ProtocolBuffers-Swift' while using this it will install 2.4.1 version but i need "Protobuf2.6-Swift3.0" this one can you help how to do that.

Thanks
ranjan kumar sahu
