### ISSUE TITLE
Support iOS simulator

### ISSUE THREAD

**Issue by schickling** [alexeyxo/protobuf-swift#90]
Is it possible to provide support for the iOS simulator as well? I'm currently getting the following error when deploying an app using this framework to the simulator:

```
dyld: Library not loaded: @rpath/ProtocolBuffers.framework/ProtocolBuffers
  Referenced from: xxx
  Reason: no suitable image found.  Did find:
	xxx/Frameworks/ProtocolBuffers.framework/ProtocolBuffers: no matching architecture in universal wrapper
```

**Comment by alexeyxo** [comment]
I have not seen such errors. Everything works fine in the simulator. I think the problem in your project settings. How do you connect the library?

**Comment by schickling** [comment]
You're absolutely right. Closing this now. Thanks!

**Comment by schmave** [comment]
In case anyone else runs across this, I fixed the error by adding `@executable_path` to the project's "Runpath search paths".
