### ISSUE TITLE
More descriptive error messages

### ISSUE THREAD

**Issue by paralin** [alexeyxo/protobuf-swift#91]
When something fails to parse, I get the following error:

```
Error: Error Domain=ProtocolBuffers.ProtocolBuffersError Code=1 "(null)"
```

This really doesn't help very much. Is there some way to get more descriptive error output?

**Comment by alexeyxo** [comment]
You should get me more descriptions about the problem. This is standart error.

**Comment by paralin** [comment]
Branch: `ProtoBuf3.0-Swift2.0`

I'll get you some more info

**Comment by alexeyxo** [comment]
You should use error handling for more description problem.
I think you got  an ```InvalidProtocolBuffer(String)``` error. The resulting array of bytes can not be read.

**Comment by paralin** [comment]
I'm waiting for a team member to post the code he uses to parse the response.

I can parse using this CLI command:

```sh
curl http://api/list/ 2>/dev/null | ./protoc.exe --proto_path=./proto/ ./proto/myapp.proto --decode=myapp.List
```

Outputs valid parsed data.

We're using proto3.

Example protobuf binary (of type MyList):

http://sprunge.us/MgQK

Protobuf definition:

```
message MyList {
     repeated MyObject things = 1;
}

message MyObject {
     string _id = 1;
     int32 state = 2;
     string uid = 3;
     int32 vis = 4;
     int64 timestamp = 5;
     SubObj loc = 6;
     SubObjs prom = 7;
     MedObj med = 8;

     message SubObj {
          double dna = 1;
          double dnb = 2;
     }
     message SubObjs {
         string thing = 1;
     }
}
message MedObj {
    string _id = 1;
    int32 typ = 2;
    string keyn = 3;
    string buck = 4;
    int32 assoctyp = 5;
    string assockey = 6;
    int32 state = 7;
    int32 partsize = 8;
    repeated bool parts = 9;
    int32 size = 10;
    string upid = 11;
}
```

**Comment by Schnei44** [comment]
Here is what we are using to parse the binary data passed back.

    let listData = try Media.MyList.parseFromData(data!)

This then errors as so:

    Error Domain=ProtocolBuffers.ProtocolBuffersError Code=1 "(null)"

**Comment by Schnei44** [comment]
Here is the ProtocolBuffersError we get: 

ProtocolBuffersError: InvalidProtocolBuffer("Invalid Tag: after tag 74")

**Comment by alexeyxo** [comment]
#92

**Comment by alexeyxo** [comment]
Error:
```
curl http://sprunge.us/MgQK 2>/dev/null | protoc tst.proto --decode=myapp.List
Type not defined: myapp.List
```

**Comment by alexeyxo** [comment]
```
curl http://sprunge.us/MgQK 2>/dev/null | protoc tst.proto --decode=MyList
Failed to parse input.
```

**Comment by paralin** [comment]
@alexeyxo It still seems to decode fine with the protoc on my computer. I'll try switching to `protobuf-net` which I believe is compatible and see if that fixes it... Will give you another binary to test with your protoc

**Comment by alexeyxo** [comment]
```
$ protoc --version
libprotoc 3.0.0
```

I downloaded your binary data. I have same result.
```
$ cat tstbin 


$2c643bea-a5c4-4cfe-a139-357d1d79140cuser1(Պ*2	7D@jܛ0U:
What is your guilty pleasure?B
$62d79950-3151-4727-b308-eb9e583a2a39(2c643bea-a5c4-4cfe-a139-357d1d79140c.mov"
                                                                               prompt-media2$2c643bea-a5c4-4cfe-a139-357d1d79140c@=JP

$ cat tstbin | protoc tst.proto --decode=MyList
Failed to parse input.

```
