### ISSUE TITLE
Getting Parser Errors when the Binary is Parsable

### ISSUE THREAD

**Issue by Schnei44** [alexeyxo/protobuf-swift#92]
We are trying to parse a proto that is encoded on our webserver then sent to our ios app.  We are able to parse the message we send out just fine using our c# parser, but when we try to parse it via swift we get:

ProtocolBuffersError: InvalidProtocolBuffer("Invalid Tag: after tag 74")

We believe this to be an error in the swift parser.  Can we discuss implementing a fix for this?

**Comment by alexeyxo** [comment]
You are sending the wrong format of the binary data. Protocol Buffers for C # is not original, it is not designed in Google. Check your data using Python/Java/C++.
Issue #91 has a same problem.

**Comment by paralin** [comment]
@alexeyxo, no, this is not true. We are using the protobuf library for c# published by Google. The binary is parseable using the official protoc executable. There is a bug in your code. Please accept that and start trying to help us find a fix. If you use the sample proto and binary posted in the other issue you can verify. 

As is the only swift protobuf library is next to useless...

**Comment by alexeyxo** [comment]
Published this does not mean that it is original... Original as only Java/C++/Python.  Give me an example of binary data that are not running. And examples Python script that parses them.

**Comment by paralin** [comment]
I did in the other issue. And i gave you a command line call you can run to test. The protoc executable is official and is as good of an example as a python script ....

**Comment by paralin** [comment]
Okay @Schnei44 you can close this..

We're back to proto 2.6 now with `protobuf-net` instead. Just going to go ahead and assume the proto3 stuff isn't stable yet.
