### ISSUE TITLE
Carthage build fails with last release and master

### ISSUE THREAD

**Issue by samgreen** [alexeyxo/protobuf-swift#93]
Hey thanks for the awesome library. Using it in a tvOS game to support party style networking. Just wanted to drop you a line that building the tvOS target fails with carthage since code signing is disabled. Silly I know, but if you could fix this up in master I'm sure it would save others some time.

**Comment by alexeyxo** [comment]
Currently, I don't know how fix this.

**Comment by samgreen** [comment]
Hey @alexeyxo no worries. I'll submit a PR. Was lucky to get a dev kit.

**Comment by samgreen** [comment]
@alexeyxo It's fixed on master with your latest changes. If you push a release it won't require specifying master in the `Cartfile` to work with tvOS.

Thanks!
